// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class AdListRes extends Message {

  public static final Integer DEFAULT_PAGE = 0;
  public static final List<AdEntity> DEFAULT_ENTITIES = Collections.emptyList();

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer page;

  /**
   * 所在页面
   */
  @ProtoField(tag = 2)
  public final MessageBody adbody;

  /**
   * 广告 MessageBody.Ad
   */
  @ProtoField(tag = 3, label = REPEATED)
  public final List<AdEntity> entities;

  private AdListRes(Builder builder) {
    this.page = builder.page;
    this.adbody = builder.adbody;
    this.entities = immutableCopyOf(builder.entities);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AdListRes)) return false;
    AdListRes o = (AdListRes) other;
    return equals(page, o.page)
        && equals(adbody, o.adbody)
        && equals(entities, o.entities);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = page != null ? page.hashCode() : 0;
      result = result * 37 + (adbody != null ? adbody.hashCode() : 0);
      result = result * 37 + (entities != null ? entities.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<AdListRes> {

    public Integer page;
    public MessageBody adbody;
    public List<AdEntity> entities;

    public Builder() {
    }

    public Builder(AdListRes message) {
      super(message);
      if (message == null) return;
      this.page = message.page;
      this.adbody = message.adbody;
      this.entities = copyOf(message.entities);
    }

    public Builder page(Integer page) {
      this.page = page;
      return this;
    }

    /**
     * 所在页面
     */
    public Builder adbody(MessageBody adbody) {
      this.adbody = adbody;
      return this;
    }

    /**
     * 广告 MessageBody.Ad
     */
    public Builder entities(List<AdEntity> entities) {
      this.entities = checkForNulls(entities);
      return this;
    }

    @Override
    public AdListRes build() {
      checkRequiredFields();
      return new AdListRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
