// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class AdRemoveReq extends Message {

  public static final Integer DEFAULT_PAGE = 0;
  public static final Integer DEFAULT_ID = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer page;

  /**
   * 所在页面
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer id;

  private AdRemoveReq(Builder builder) {
    this.page = builder.page;
    this.id = builder.id;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AdRemoveReq)) return false;
    AdRemoveReq o = (AdRemoveReq) other;
    return equals(page, o.page)
        && equals(id, o.id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = page != null ? page.hashCode() : 0;
      result = result * 37 + (id != null ? id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<AdRemoveReq> {

    public Integer page;
    public Integer id;

    public Builder() {
    }

    public Builder(AdRemoveReq message) {
      super(message);
      if (message == null) return;
      this.page = message.page;
      this.id = message.id;
    }

    public Builder page(Integer page) {
      this.page = page;
      return this;
    }

    /**
     * 所在页面
     */
    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    @Override
    public AdRemoveReq build() {
      checkRequiredFields();
      return new AdRemoveReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
