// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum CardColor
    implements ProtoEnum {
  CardColor_Diamond(0),
  /**
   * 方块
   */
  CardColor_Club(1),
  /**
   * 梅花
   */
  CardColor_Heart(2),
  /**
   * 红桃
   */
  CardColor_Spade(3);

  private final int value;

  private CardColor(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int CardColor_Diamond_VALUE = 0;
  /**
   * 方块
   */
  public static final int CardColor_Club_VALUE = 1;
  /**
   * 梅花
   */
  public static final int CardColor_Heart_VALUE = 2;
  /**
   * 红桃
   */
  public static final int CardColor_Spade_VALUE = 3;

  public static CardColor valueOf(int value) {
    switch (value)  {
      case 0: return CardColor_Diamond;
      case 1: return CardColor_Club;
      case 2: return CardColor_Heart;
      case 3: return CardColor_Spade;
      default: return null;
    }
  }
}
