// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class ChatMsgInfo extends Message {

  public static final String DEFAULT_MSG = "";
  public static final Long DEFAULT_MSGID = 0L;
  public static final MsgType DEFAULT_MSGTYPE = MsgType.SendMsg;
  public static final Long DEFAULT_CREATETIME = 0L;

  @ProtoField(tag = 1, type = STRING)
  public final String msg;

  /**
   * MessageBody json
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long msgId;

  @ProtoField(tag = 3, type = ENUM)
  public final MsgType msgType;

  @ProtoField(tag = 4, type = INT64)
  public final Long createTime;

  private ChatMsgInfo(Builder builder) {
    this.msg = builder.msg;
    this.msgId = builder.msgId;
    this.msgType = builder.msgType;
    this.createTime = builder.createTime;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ChatMsgInfo)) return false;
    ChatMsgInfo o = (ChatMsgInfo) other;
    return equals(msg, o.msg)
        && equals(msgId, o.msgId)
        && equals(msgType, o.msgType)
        && equals(createTime, o.createTime);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = msg != null ? msg.hashCode() : 0;
      result = result * 37 + (msgId != null ? msgId.hashCode() : 0);
      result = result * 37 + (msgType != null ? msgType.hashCode() : 0);
      result = result * 37 + (createTime != null ? createTime.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ChatMsgInfo> {

    public String msg;
    public Long msgId;
    public MsgType msgType;
    public Long createTime;

    public Builder() {
    }

    public Builder(ChatMsgInfo message) {
      super(message);
      if (message == null) return;
      this.msg = message.msg;
      this.msgId = message.msgId;
      this.msgType = message.msgType;
      this.createTime = message.createTime;
    }

    public Builder msg(String msg) {
      this.msg = msg;
      return this;
    }

    /**
     * MessageBody json
     */
    public Builder msgId(Long msgId) {
      this.msgId = msgId;
      return this;
    }

    public Builder msgType(MsgType msgType) {
      this.msgType = msgType;
      return this;
    }

    public Builder createTime(Long createTime) {
      this.createTime = createTime;
      return this;
    }

    @Override
    public ChatMsgInfo build() {
      return new ChatMsgInfo(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
