// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum DevType
    implements ProtoEnum {
  DevType_Unknown(0),
  DevType_Android(1),
  DevType_Ios(2),
  DevType_Pc(3),
  DevType_Web(4),
  DevType_Sdk(5),
  DevType_Robot(6);

  private final int value;

  private DevType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int DevType_Unknown_VALUE = 0;
  public static final int DevType_Android_VALUE = 1;
  public static final int DevType_Ios_VALUE = 2;
  public static final int DevType_Pc_VALUE = 3;
  public static final int DevType_Web_VALUE = 4;
  public static final int DevType_Sdk_VALUE = 5;
  public static final int DevType_Robot_VALUE = 6;

  public static DevType valueOf(int value) {
    switch (value)  {
      case 0: return DevType_Unknown;
      case 1: return DevType_Android;
      case 2: return DevType_Ios;
      case 3: return DevType_Pc;
      case 4: return DevType_Web;
      case 5: return DevType_Sdk;
      case 6: return DevType_Robot;
      default: return null;
    }
  }
}
