// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum EncryptType
    implements ProtoEnum {
  EncryptTypeNone(0),
  EncryptTypeRC4(1);

  private final int value;

  private EncryptType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int EncryptTypeNone_VALUE = 0;
  public static final int EncryptTypeRC4_VALUE = 1;

  public static EncryptType valueOf(int value) {
    switch (value)  {
      case 0: return EncryptTypeNone;
      case 1: return EncryptTypeRC4;
      default: return null;
    }
  }
}
