// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class FollowItReq extends Message {

  public static final Long DEFAULT_UID = 0L;
  public static final Long DEFAULT_GID = 0L;
  public static final List<Long> DEFAULT_UIDS = Collections.emptyList();

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long uid;

  @ProtoField(tag = 2, type = UINT64)
  public final Long gid;

  /**
   * 在直播间中关注的用户
   */
  @ProtoField(tag = 3, type = UINT64, label = REPEATED)
  public final List<Long> uids;

  private FollowItReq(Builder builder) {
    this.uid = builder.uid;
    this.gid = builder.gid;
    this.uids = immutableCopyOf(builder.uids);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FollowItReq)) return false;
    FollowItReq o = (FollowItReq) other;
    return equals(uid, o.uid)
        && equals(gid, o.gid)
        && equals(uids, o.uids);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uid != null ? uid.hashCode() : 0;
      result = result * 37 + (gid != null ? gid.hashCode() : 0);
      result = result * 37 + (uids != null ? uids.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<FollowItReq> {

    public Long uid;
    public Long gid;
    public List<Long> uids;

    public Builder() {
    }

    public Builder(FollowItReq message) {
      super(message);
      if (message == null) return;
      this.uid = message.uid;
      this.gid = message.gid;
      this.uids = copyOf(message.uids);
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder gid(Long gid) {
      this.gid = gid;
      return this;
    }

    /**
     * 在直播间中关注的用户
     */
    public Builder uids(List<Long> uids) {
      this.uids = checkForNulls(uids);
      return this;
    }

    @Override
    public FollowItReq build() {
      checkRequiredFields();
      return new FollowItReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
