// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;

public final class FollowListRes extends Message {

  public static final Integer DEFAULT_INDEX = 0;
  public static final Integer DEFAULT_FETCHS = 0;
  public static final Long DEFAULT_UID = 0L;
  public static final Integer DEFAULT_TOTALRESULTS = 0;
  public static final List<Fan> DEFAULT_FOLLOWS = Collections.emptyList();
  public static final Boolean DEFAULT_HASMORE = false;

  @ProtoField(tag = 1, type = UINT32)
  public final Integer index;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer fetchs;

  @ProtoField(tag = 5, type = UINT64)
  public final Long uid;

  @ProtoField(tag = 11, type = UINT32)
  public final Integer totalresults;

  /**
   * 暂时不用
   */
  @ProtoField(tag = 10, label = REPEATED)
  public final List<Fan> follows;

  @ProtoField(tag = 13, type = BOOL)
  public final Boolean hasmore;

  private FollowListRes(Builder builder) {
    this.index = builder.index;
    this.fetchs = builder.fetchs;
    this.uid = builder.uid;
    this.totalresults = builder.totalresults;
    this.follows = immutableCopyOf(builder.follows);
    this.hasmore = builder.hasmore;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FollowListRes)) return false;
    FollowListRes o = (FollowListRes) other;
    return equals(index, o.index)
        && equals(fetchs, o.fetchs)
        && equals(uid, o.uid)
        && equals(totalresults, o.totalresults)
        && equals(follows, o.follows)
        && equals(hasmore, o.hasmore);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = index != null ? index.hashCode() : 0;
      result = result * 37 + (fetchs != null ? fetchs.hashCode() : 0);
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      result = result * 37 + (totalresults != null ? totalresults.hashCode() : 0);
      result = result * 37 + (follows != null ? follows.hashCode() : 1);
      result = result * 37 + (hasmore != null ? hasmore.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<FollowListRes> {

    public Integer index;
    public Integer fetchs;
    public Long uid;
    public Integer totalresults;
    public List<Fan> follows;
    public Boolean hasmore;

    public Builder() {
    }

    public Builder(FollowListRes message) {
      super(message);
      if (message == null) return;
      this.index = message.index;
      this.fetchs = message.fetchs;
      this.uid = message.uid;
      this.totalresults = message.totalresults;
      this.follows = copyOf(message.follows);
      this.hasmore = message.hasmore;
    }

    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    public Builder fetchs(Integer fetchs) {
      this.fetchs = fetchs;
      return this;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder totalresults(Integer totalresults) {
      this.totalresults = totalresults;
      return this;
    }

    /**
     * 暂时不用
     */
    public Builder follows(List<Fan> follows) {
      this.follows = checkForNulls(follows);
      return this;
    }

    public Builder hasmore(Boolean hasmore) {
      this.hasmore = hasmore;
      return this;
    }

    @Override
    public FollowListRes build() {
      return new FollowListRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
