// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 根据code获取openid
 */
public final class GetWxOpenidReq extends Message {

  public static final String DEFAULT_CODE = "";

  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String code;

  private GetWxOpenidReq(Builder builder) {
    this.code = builder.code;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetWxOpenidReq)) return false;
    return equals(code, ((GetWxOpenidReq) other).code);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = code != null ? code.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<GetWxOpenidReq> {

    public String code;

    public Builder() {
    }

    public Builder(GetWxOpenidReq message) {
      super(message);
      if (message == null) return;
      this.code = message.code;
    }

    public Builder code(String code) {
      this.code = code;
      return this;
    }

    @Override
    public GetWxOpenidReq build() {
      checkRequiredFields();
      return new GetWxOpenidReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
