// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 根据code获取openid
 */
public final class GetWxOpenidRes extends Message {

  public static final String DEFAULT_OPENID = "";

  @ProtoField(tag = 1, type = STRING)
  public final String openid;

  private GetWxOpenidRes(Builder builder) {
    this.openid = builder.openid;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetWxOpenidRes)) return false;
    return equals(openid, ((GetWxOpenidRes) other).openid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = openid != null ? openid.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<GetWxOpenidRes> {

    public String openid;

    public Builder() {
    }

    public Builder(GetWxOpenidRes message) {
      super(message);
      if (message == null) return;
      this.openid = message.openid;
    }

    public Builder openid(String openid) {
      this.openid = openid;
      return this;
    }

    @Override
    public GetWxOpenidRes build() {
      return new GetWxOpenidRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
