// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class GiftRecordItem extends Message {

  public static final Long DEFAULT_ID = 0L;
  public static final Long DEFAULT_DONORUID = 0L;
  public static final Integer DEFAULT_GIFTID = 0;
  public static final Integer DEFAULT_NUM = 1;
  public static final Long DEFAULT_CREATETIME = 0L;

  @ProtoField(tag = 1, type = UINT64)
  public final Long id;

  @ProtoField(tag = 2)
  public final UserInfo donor;

  /**
   * 送礼人
   */
  @ProtoField(tag = 3, type = UINT64)
  public final Long donorUid;

  /**
   * 送礼人UID（客户端不用这个）
   */
  @ProtoField(tag = 4, type = UINT32)
  public final Integer giftId;

  @ProtoField(tag = 5, type = UINT32)
  public final Integer num;

  @ProtoField(tag = 6, type = INT64)
  public final Long createtime;

  private GiftRecordItem(Builder builder) {
    this.id = builder.id;
    this.donor = builder.donor;
    this.donorUid = builder.donorUid;
    this.giftId = builder.giftId;
    this.num = builder.num;
    this.createtime = builder.createtime;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GiftRecordItem)) return false;
    GiftRecordItem o = (GiftRecordItem) other;
    return equals(id, o.id)
        && equals(donor, o.donor)
        && equals(donorUid, o.donorUid)
        && equals(giftId, o.giftId)
        && equals(num, o.num)
        && equals(createtime, o.createtime);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = id != null ? id.hashCode() : 0;
      result = result * 37 + (donor != null ? donor.hashCode() : 0);
      result = result * 37 + (donorUid != null ? donorUid.hashCode() : 0);
      result = result * 37 + (giftId != null ? giftId.hashCode() : 0);
      result = result * 37 + (num != null ? num.hashCode() : 0);
      result = result * 37 + (createtime != null ? createtime.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GiftRecordItem> {

    public Long id;
    public UserInfo donor;
    public Long donorUid;
    public Integer giftId;
    public Integer num;
    public Long createtime;

    public Builder() {
    }

    public Builder(GiftRecordItem message) {
      super(message);
      if (message == null) return;
      this.id = message.id;
      this.donor = message.donor;
      this.donorUid = message.donorUid;
      this.giftId = message.giftId;
      this.num = message.num;
      this.createtime = message.createtime;
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    public Builder donor(UserInfo donor) {
      this.donor = donor;
      return this;
    }

    /**
     * 送礼人
     */
    public Builder donorUid(Long donorUid) {
      this.donorUid = donorUid;
      return this;
    }

    /**
     * 送礼人UID（客户端不用这个）
     */
    public Builder giftId(Integer giftId) {
      this.giftId = giftId;
      return this;
    }

    public Builder num(Integer num) {
      this.num = num;
      return this;
    }

    public Builder createtime(Long createtime) {
      this.createtime = createtime;
      return this;
    }

    @Override
    public GiftRecordItem build() {
      return new GiftRecordItem(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
