// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum GiftType
    implements ProtoEnum {
  Gift_MGold(0),
  Gift_MChip(1),
  Gift_MGoldRedBag(2),
  Gift_MChipRedBag(3),
  Gift_MGoldDraw(4),
  Gift_MChipDraw(5);

  private final int value;

  private GiftType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int Gift_MGold_VALUE = 0;
  public static final int Gift_MChip_VALUE = 1;
  public static final int Gift_MGoldRedBag_VALUE = 2;
  public static final int Gift_MChipRedBag_VALUE = 3;
  public static final int Gift_MGoldDraw_VALUE = 4;
  public static final int Gift_MChipDraw_VALUE = 5;

  public static GiftType valueOf(int value) {
    switch (value)  {
      case 0: return Gift_MGold;
      case 1: return Gift_MChip;
      case 2: return Gift_MGoldRedBag;
      case 3: return Gift_MChipRedBag;
      case 4: return Gift_MGoldDraw;
      case 5: return Gift_MChipDraw;
      default: return null;
    }
  }
}
