// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class GiftListReq extends Message {

  public static final Integer DEFAULT_INDEX = 0;
  public static final Integer DEFAULT_FETCHS = 0;
  public static final List<GiftType> DEFAULT_GIFTTYPE = Collections.emptyList();

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer index;

  @ProtoField(tag = 2, type = UINT32, label = REQUIRED)
  public final Integer fetchs;

  @ProtoField(tag = 3, type = ENUM, label = REPEATED)
  public final List<GiftType> giftType;

  private GiftListReq(Builder builder) {
    this.index = builder.index;
    this.fetchs = builder.fetchs;
    this.giftType = immutableCopyOf(builder.giftType);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GiftListReq)) return false;
    GiftListReq o = (GiftListReq) other;
    return equals(index, o.index)
        && equals(fetchs, o.fetchs)
        && equals(giftType, o.giftType);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = index != null ? index.hashCode() : 0;
      result = result * 37 + (fetchs != null ? fetchs.hashCode() : 0);
      result = result * 37 + (giftType != null ? giftType.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GiftListReq> {

    public Integer index;
    public Integer fetchs;
    public List<GiftType> giftType;

    public Builder() {
    }

    public Builder(GiftListReq message) {
      super(message);
      if (message == null) return;
      this.index = message.index;
      this.fetchs = message.fetchs;
      this.giftType = copyOf(message.giftType);
    }

    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    public Builder fetchs(Integer fetchs) {
      this.fetchs = fetchs;
      return this;
    }

    public Builder giftType(List<GiftType> giftType) {
      this.giftType = checkForNulls(giftType);
      return this;
    }

    @Override
    public GiftListReq build() {
      checkRequiredFields();
      return new GiftListReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
