// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class GrabRedBagRes extends Message {

  public static final Long DEFAULT_BAGID = 0L;
  public static final Long DEFAULT_GETVALUE = 0L;
  public static final Integer DEFAULT_GIFTID = 0;

  @ProtoField(tag = 1, type = UINT64)
  public final Long bagId;

  @ProtoField(tag = 2, type = INT64)
  public final Long getValue;

  @ProtoField(tag = 3, type = UINT32)
  public final Integer giftId;

  private GrabRedBagRes(Builder builder) {
    this.bagId = builder.bagId;
    this.getValue = builder.getValue;
    this.giftId = builder.giftId;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GrabRedBagRes)) return false;
    GrabRedBagRes o = (GrabRedBagRes) other;
    return equals(bagId, o.bagId)
        && equals(getValue, o.getValue)
        && equals(giftId, o.giftId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = bagId != null ? bagId.hashCode() : 0;
      result = result * 37 + (getValue != null ? getValue.hashCode() : 0);
      result = result * 37 + (giftId != null ? giftId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GrabRedBagRes> {

    public Long bagId;
    public Long getValue;
    public Integer giftId;

    public Builder() {
    }

    public Builder(GrabRedBagRes message) {
      super(message);
      if (message == null) return;
      this.bagId = message.bagId;
      this.getValue = message.getValue;
      this.giftId = message.giftId;
    }

    public Builder bagId(Long bagId) {
      this.bagId = bagId;
      return this;
    }

    public Builder getValue(Long getValue) {
      this.getValue = getValue;
      return this;
    }

    public Builder giftId(Integer giftId) {
      this.giftId = giftId;
      return this;
    }

    @Override
    public GrabRedBagRes build() {
      return new GrabRedBagRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
