// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class GroupMsgListRes extends Message {

  public static final List<GroupMsgList> DEFAULT_MSGLISTS = Collections.emptyList();
  public static final List<UserInfo> DEFAULT_USERS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<GroupMsgList> msglists;

  @ProtoField(tag = 2, label = REPEATED)
  public final List<UserInfo> users;

  private GroupMsgListRes(Builder builder) {
    this.msglists = immutableCopyOf(builder.msglists);
    this.users = immutableCopyOf(builder.users);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupMsgListRes)) return false;
    GroupMsgListRes o = (GroupMsgListRes) other;
    return equals(msglists, o.msglists)
        && equals(users, o.users);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = msglists != null ? msglists.hashCode() : 1;
      result = result * 37 + (users != null ? users.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GroupMsgListRes> {

    public List<GroupMsgList> msglists;
    public List<UserInfo> users;

    public Builder() {
    }

    public Builder(GroupMsgListRes message) {
      super(message);
      if (message == null) return;
      this.msglists = copyOf(message.msglists);
      this.users = copyOf(message.users);
    }

    public Builder msglists(List<GroupMsgList> msglists) {
      this.msglists = checkForNulls(msglists);
      return this;
    }

    public Builder users(List<UserInfo> users) {
      this.users = checkForNulls(users);
      return this;
    }

    @Override
    public GroupMsgListRes build() {
      return new GroupMsgListRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
