// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum GroupApprove
    implements ProtoEnum {
  Needless(0),
  /**
   * 公开，不需要批准直接通过
   */
  NeedApprove(1),
  /**
   * 需要批准申请
   */
  RefuseAnybody(2),
  /**
   * 拒绝任何人
   */
  Password(3);

  private final int value;

  private GroupApprove(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int Needless_VALUE = 0;
  /**
   * 公开，不需要批准直接通过
   */
  public static final int NeedApprove_VALUE = 1;
  /**
   * 需要批准申请
   */
  public static final int RefuseAnybody_VALUE = 2;
  /**
   * 拒绝任何人
   */
  public static final int Password_VALUE = 3;

  public static GroupApprove valueOf(int value) {
    switch (value)  {
      case 0: return Needless;
      case 1: return NeedApprove;
      case 2: return RefuseAnybody;
      case 3: return Password;
      default: return null;
    }
  }
}
