// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum GroupState
    implements ProtoEnum {
  GroupState_Unknown(0),
  GroupState_OK(1),
  GroupState_Freeze(3),
  GroupState_Destroy(4);

  private final int value;

  private GroupState(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int GroupState_Unknown_VALUE = 0;
  public static final int GroupState_OK_VALUE = 1;
  public static final int GroupState_Freeze_VALUE = 3;
  public static final int GroupState_Destroy_VALUE = 4;

  public static GroupState valueOf(int value) {
    switch (value)  {
      case 0: return GroupState_Unknown;
      case 1: return GroupState_OK;
      case 3: return GroupState_Freeze;
      case 4: return GroupState_Destroy;
      default: return null;
    }
  }
}
