// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class GroupMemberList extends Message {

  public static final List<GroupMember> DEFAULT_MEMBERS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<GroupMember> members;

  private GroupMemberList(Builder builder) {
    this.members = immutableCopyOf(builder.members);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupMemberList)) return false;
    return equals(members, ((GroupMemberList) other).members);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = members != null ? members.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<GroupMemberList> {

    public List<GroupMember> members;

    public Builder() {
    }

    public Builder(GroupMemberList message) {
      super(message);
      if (message == null) return;
      this.members = copyOf(message.members);
    }

    public Builder members(List<GroupMember> members) {
      this.members = checkForNulls(members);
      return this;
    }

    @Override
    public GroupMemberList build() {
      return new GroupMemberList(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
