// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum GroupMsgSortBy
    implements ProtoEnum {
  GroupMsgSortByRevision(0),
  GroupMsgSortByConsentCount(1),
  GroupMsgSortByTopTime(2);

  private final int value;

  private GroupMsgSortBy(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int GroupMsgSortByRevision_VALUE = 0;
  public static final int GroupMsgSortByConsentCount_VALUE = 1;
  public static final int GroupMsgSortByTopTime_VALUE = 2;

  public static GroupMsgSortBy valueOf(int value) {
    switch (value)  {
      case 0: return GroupMsgSortByRevision;
      case 1: return GroupMsgSortByConsentCount;
      case 2: return GroupMsgSortByTopTime;
      default: return null;
    }
  }
}
