// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class GroupDestroyRes extends Message {

  public static final Long DEFAULT_GID = 0L;
  public static final Integer DEFAULT_MEMBERS = 0;
  public static final Long DEFAULT_WINBETS = 0L;
  public static final Long DEFAULT_LOVEVAL = 0L;
  public static final Long DEFAULT_MBEANS = 0L;
  public static final Integer DEFAULT_FANS = 0;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long gid;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer members;

  /**
   * 观看过的人数
   */
  @ProtoField(tag = 3, type = INT64)
  public final Long winBets;

  /**
   * 在这场直播中赢的筹码
   */
  @ProtoField(tag = 4, type = UINT64)
  public final Long loveVal;

  /**
   * 新增的亲密值
   */
  @ProtoField(tag = 5, type = UINT64)
  public final Long mbeans;

  /**
   * 新增的M豆
   */
  @ProtoField(tag = 6, type = UINT32)
  public final Integer fans;

  private GroupDestroyRes(Builder builder) {
    this.gid = builder.gid;
    this.members = builder.members;
    this.winBets = builder.winBets;
    this.loveVal = builder.loveVal;
    this.mbeans = builder.mbeans;
    this.fans = builder.fans;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupDestroyRes)) return false;
    GroupDestroyRes o = (GroupDestroyRes) other;
    return equals(gid, o.gid)
        && equals(members, o.members)
        && equals(winBets, o.winBets)
        && equals(loveVal, o.loveVal)
        && equals(mbeans, o.mbeans)
        && equals(fans, o.fans);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = gid != null ? gid.hashCode() : 0;
      result = result * 37 + (members != null ? members.hashCode() : 0);
      result = result * 37 + (winBets != null ? winBets.hashCode() : 0);
      result = result * 37 + (loveVal != null ? loveVal.hashCode() : 0);
      result = result * 37 + (mbeans != null ? mbeans.hashCode() : 0);
      result = result * 37 + (fans != null ? fans.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GroupDestroyRes> {

    public Long gid;
    public Integer members;
    public Long winBets;
    public Long loveVal;
    public Long mbeans;
    public Integer fans;

    public Builder() {
    }

    public Builder(GroupDestroyRes message) {
      super(message);
      if (message == null) return;
      this.gid = message.gid;
      this.members = message.members;
      this.winBets = message.winBets;
      this.loveVal = message.loveVal;
      this.mbeans = message.mbeans;
      this.fans = message.fans;
    }

    public Builder gid(Long gid) {
      this.gid = gid;
      return this;
    }

    public Builder members(Integer members) {
      this.members = members;
      return this;
    }

    /**
     * 观看过的人数
     */
    public Builder winBets(Long winBets) {
      this.winBets = winBets;
      return this;
    }

    /**
     * 在这场直播中赢的筹码
     */
    public Builder loveVal(Long loveVal) {
      this.loveVal = loveVal;
      return this;
    }

    /**
     * 新增的亲密值
     */
    public Builder mbeans(Long mbeans) {
      this.mbeans = mbeans;
      return this;
    }

    /**
     * 新增的M豆
     */
    public Builder fans(Integer fans) {
      this.fans = fans;
      return this;
    }

    @Override
    public GroupDestroyRes build() {
      checkRequiredFields();
      return new GroupDestroyRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
