// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class GroupMapReq extends Message {

  public static final String DEFAULT_PASSWORD = "";

  @ProtoField(tag = 1, type = STRING)
  public final String password;

  private GroupMapReq(Builder builder) {
    this.password = builder.password;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupMapReq)) return false;
    return equals(password, ((GroupMapReq) other).password);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = password != null ? password.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<GroupMapReq> {

    public String password;

    public Builder() {
    }

    public Builder(GroupMapReq message) {
      super(message);
      if (message == null) return;
      this.password = message.password;
    }

    public Builder password(String password) {
      this.password = password;
      return this;
    }

    @Override
    public GroupMapReq build() {
      return new GroupMapReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
