// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;

public final class GroupMemberRolerSetReq extends Message {

  public static final Long DEFAULT_GID = 0L;

  @ProtoField(tag = 1, type = UINT64)
  public final Long gid;

  @ProtoField(tag = 2)
  public final GroupMemberRolerItem item;

  private GroupMemberRolerSetReq(Builder builder) {
    this.gid = builder.gid;
    this.item = builder.item;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupMemberRolerSetReq)) return false;
    GroupMemberRolerSetReq o = (GroupMemberRolerSetReq) other;
    return equals(gid, o.gid)
        && equals(item, o.item);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = gid != null ? gid.hashCode() : 0;
      result = result * 37 + (item != null ? item.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GroupMemberRolerSetReq> {

    public Long gid;
    public GroupMemberRolerItem item;

    public Builder() {
    }

    public Builder(GroupMemberRolerSetReq message) {
      super(message);
      if (message == null) return;
      this.gid = message.gid;
      this.item = message.item;
    }

    public Builder gid(Long gid) {
      this.gid = gid;
      return this;
    }

    public Builder item(GroupMemberRolerItem item) {
      this.item = item;
      return this;
    }

    @Override
    public GroupMemberRolerSetReq build() {
      return new GroupMemberRolerSetReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
