// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 发送群消息
 */
public final class GroupMsgSendReq extends Message {

  public static final Long DEFAULT_GID = 0L;

  @ProtoField(tag = 1, type = UINT64)
  public final Long gid;

  @ProtoField(tag = 2)
  public final GroupMsg msg;

  private GroupMsgSendReq(Builder builder) {
    this.gid = builder.gid;
    this.msg = builder.msg;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupMsgSendReq)) return false;
    GroupMsgSendReq o = (GroupMsgSendReq) other;
    return equals(gid, o.gid)
        && equals(msg, o.msg);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = gid != null ? gid.hashCode() : 0;
      result = result * 37 + (msg != null ? msg.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GroupMsgSendReq> {

    public Long gid;
    public GroupMsg msg;

    public Builder() {
    }

    public Builder(GroupMsgSendReq message) {
      super(message);
      if (message == null) return;
      this.gid = message.gid;
      this.msg = message.msg;
    }

    public Builder gid(Long gid) {
      this.gid = gid;
      return this;
    }

    public Builder msg(GroupMsg msg) {
      this.msg = msg;
      return this;
    }

    @Override
    public GroupMsgSendReq build() {
      return new GroupMsgSendReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
