// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class GroupMsgApp extends Message {

  public static final Long DEFAULT_REFMSG = 0L;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long refmsg;

  private GroupMsgApp(Builder builder) {
    this.refmsg = builder.refmsg;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupMsgApp)) return false;
    return equals(refmsg, ((GroupMsgApp) other).refmsg);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = refmsg != null ? refmsg.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<GroupMsgApp> {

    public Long refmsg;

    public Builder() {
    }

    public Builder(GroupMsgApp message) {
      super(message);
      if (message == null) return;
      this.refmsg = message.refmsg;
    }

    public Builder refmsg(Long refmsg) {
      this.refmsg = refmsg;
      return this;
    }

    @Override
    public GroupMsgApp build() {
      checkRequiredFields();
      return new GroupMsgApp(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
