// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;

public final class GroupMemberListReq extends Message {

  public static final Long DEFAULT_GID = 0L;
  public static final Long DEFAULT_REVISION = 0L;

  @ProtoField(tag = 1, type = UINT64)
  public final Long gid;

  @ProtoField(tag = 2, type = UINT64)
  public final Long revision;

  private GroupMemberListReq(Builder builder) {
    this.gid = builder.gid;
    this.revision = builder.revision;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupMemberListReq)) return false;
    GroupMemberListReq o = (GroupMemberListReq) other;
    return equals(gid, o.gid)
        && equals(revision, o.revision);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = gid != null ? gid.hashCode() : 0;
      result = result * 37 + (revision != null ? revision.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GroupMemberListReq> {

    public Long gid;
    public Long revision;

    public Builder() {
    }

    public Builder(GroupMemberListReq message) {
      super(message);
      if (message == null) return;
      this.gid = message.gid;
      this.revision = message.revision;
    }

    public Builder gid(Long gid) {
      this.gid = gid;
      return this;
    }

    public Builder revision(Long revision) {
      this.revision = revision;
      return this;
    }

    @Override
    public GroupMemberListReq build() {
      return new GroupMemberListReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
