// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class GroupSearchReq extends Message {

  public static final String DEFAULT_KEYWORD = "";
  public static final Integer DEFAULT_INDEX = 0;
  public static final Integer DEFAULT_FETCHS = 0;
  public static final GroupType DEFAULT_GTYPE = GroupType.Group_Unknown;
  public static final GroupSearchBy DEFAULT_SEARCHBY = GroupSearchBy.GroupSearchByUnknown;
  public static final GroupSearchOrderBy DEFAULT_ORDERBY = GroupSearchOrderBy.GroupSearchOrderByDesc;
  public static final Integer DEFAULT_GAMEID = 0;
  public static final Long DEFAULT_GIFTID = 0L;
  public static final Long DEFAULT_CACHEKEY = 0L;

  @ProtoField(tag = 1, type = STRING)
  public final String keyword;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer index;

  /**
   * 从第几个结果开始
   */
  @ProtoField(tag = 3, type = UINT32)
  public final Integer fetchs;

  /**
   * 取多少个结果
   */
  @ProtoField(tag = 5, type = ENUM)
  public final GroupType gtype;

  @ProtoField(tag = 10, type = ENUM)
  public final GroupSearchBy searchBy;

  /**
   * 排序方式
   */
  @ProtoField(tag = 11, type = ENUM)
  public final GroupSearchOrderBy orderBy;

  /**
   * 升序或降序
   */
  @ProtoField(tag = 15)
  public final GroupInfo template;

  @ProtoField(tag = 16, type = UINT32)
  public final Integer gameid;

  /**
   * 游戏id
   */
  @ProtoField(tag = 17, type = UINT64)
  public final Long giftid;

  /**
   * 礼包id  (查找有某款游戏礼包的公会列表)
   */
  @ProtoField(tag = 100, type = UINT64)
  public final Long cacheKey;

  private GroupSearchReq(Builder builder) {
    this.keyword = builder.keyword;
    this.index = builder.index;
    this.fetchs = builder.fetchs;
    this.gtype = builder.gtype;
    this.searchBy = builder.searchBy;
    this.orderBy = builder.orderBy;
    this.template = builder.template;
    this.gameid = builder.gameid;
    this.giftid = builder.giftid;
    this.cacheKey = builder.cacheKey;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GroupSearchReq)) return false;
    GroupSearchReq o = (GroupSearchReq) other;
    return equals(keyword, o.keyword)
        && equals(index, o.index)
        && equals(fetchs, o.fetchs)
        && equals(gtype, o.gtype)
        && equals(searchBy, o.searchBy)
        && equals(orderBy, o.orderBy)
        && equals(template, o.template)
        && equals(gameid, o.gameid)
        && equals(giftid, o.giftid)
        && equals(cacheKey, o.cacheKey);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = keyword != null ? keyword.hashCode() : 0;
      result = result * 37 + (index != null ? index.hashCode() : 0);
      result = result * 37 + (fetchs != null ? fetchs.hashCode() : 0);
      result = result * 37 + (gtype != null ? gtype.hashCode() : 0);
      result = result * 37 + (searchBy != null ? searchBy.hashCode() : 0);
      result = result * 37 + (orderBy != null ? orderBy.hashCode() : 0);
      result = result * 37 + (template != null ? template.hashCode() : 0);
      result = result * 37 + (gameid != null ? gameid.hashCode() : 0);
      result = result * 37 + (giftid != null ? giftid.hashCode() : 0);
      result = result * 37 + (cacheKey != null ? cacheKey.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GroupSearchReq> {

    public String keyword;
    public Integer index;
    public Integer fetchs;
    public GroupType gtype;
    public GroupSearchBy searchBy;
    public GroupSearchOrderBy orderBy;
    public GroupInfo template;
    public Integer gameid;
    public Long giftid;
    public Long cacheKey;

    public Builder() {
    }

    public Builder(GroupSearchReq message) {
      super(message);
      if (message == null) return;
      this.keyword = message.keyword;
      this.index = message.index;
      this.fetchs = message.fetchs;
      this.gtype = message.gtype;
      this.searchBy = message.searchBy;
      this.orderBy = message.orderBy;
      this.template = message.template;
      this.gameid = message.gameid;
      this.giftid = message.giftid;
      this.cacheKey = message.cacheKey;
    }

    public Builder keyword(String keyword) {
      this.keyword = keyword;
      return this;
    }

    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    /**
     * 从第几个结果开始
     */
    public Builder fetchs(Integer fetchs) {
      this.fetchs = fetchs;
      return this;
    }

    /**
     * 取多少个结果
     */
    public Builder gtype(GroupType gtype) {
      this.gtype = gtype;
      return this;
    }

    public Builder searchBy(GroupSearchBy searchBy) {
      this.searchBy = searchBy;
      return this;
    }

    /**
     * 排序方式
     */
    public Builder orderBy(GroupSearchOrderBy orderBy) {
      this.orderBy = orderBy;
      return this;
    }

    /**
     * 升序或降序
     */
    public Builder template(GroupInfo template) {
      this.template = template;
      return this;
    }

    public Builder gameid(Integer gameid) {
      this.gameid = gameid;
      return this;
    }

    /**
     * 游戏id
     */
    public Builder giftid(Long giftid) {
      this.giftid = giftid;
      return this;
    }

    /**
     * 礼包id  (查找有某款游戏礼包的公会列表)
     */
    public Builder cacheKey(Long cacheKey) {
      this.cacheKey = cacheKey;
      return this;
    }

    @Override
    public GroupSearchReq build() {
      return new GroupSearchReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
