// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum GroupMemberCountType
    implements ProtoEnum {
  GroupMemberCountAllOnline(0);

  private final int value;

  private GroupMemberCountType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int GroupMemberCountAllOnline_VALUE = 0;

  public static GroupMemberCountType valueOf(int value) {
    switch (value)  {
      case 0: return GroupMemberCountAllOnline;
      default: return null;
    }
  }
}
