// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class LivesRes extends Message {

  public static final List<UserLive> DEFAULT_LIVES = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<UserLive> lives;

  private LivesRes(Builder builder) {
    this.lives = immutableCopyOf(builder.lives);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LivesRes)) return false;
    return equals(lives, ((LivesRes) other).lives);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = lives != null ? lives.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<LivesRes> {

    public List<UserLive> lives;

    public Builder() {
    }

    public Builder(LivesRes message) {
      super(message);
      if (message == null) return;
      this.lives = copyOf(message.lives);
    }

    public Builder lives(List<UserLive> lives) {
      this.lives = checkForNulls(lives);
      return this;
    }

    @Override
    public LivesRes build() {
      return new LivesRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
