// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class LvExpConfigReq extends Message {

  private LvExpConfigReq(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof LvExpConfigReq;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<LvExpConfigReq> {

    public Builder() {
    }

    public Builder(LvExpConfigReq message) {
      super(message);
    }

    @Override
    public LvExpConfigReq build() {
      return new LvExpConfigReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
