// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 升级推送
 */
public final class LvUpPush extends Message {

  public static final Long DEFAULT_EXP = 0L;
  public static final Integer DEFAULT_LV = 0;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long exp;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer lv;

  private LvUpPush(Builder builder) {
    this.exp = builder.exp;
    this.lv = builder.lv;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LvUpPush)) return false;
    LvUpPush o = (LvUpPush) other;
    return equals(exp, o.exp)
        && equals(lv, o.lv);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = exp != null ? exp.hashCode() : 0;
      result = result * 37 + (lv != null ? lv.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LvUpPush> {

    public Long exp;
    public Integer lv;

    public Builder() {
    }

    public Builder(LvUpPush message) {
      super(message);
      if (message == null) return;
      this.exp = message.exp;
      this.lv = message.lv;
    }

    public Builder exp(Long exp) {
      this.exp = exp;
      return this;
    }

    public Builder lv(Integer lv) {
      this.lv = lv;
      return this;
    }

    @Override
    public LvUpPush build() {
      checkRequiredFields();
      return new LvUpPush(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
