// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

/**
 * 获取可购买筹码列表
 */
public final class MChipItemReq extends Message {

  private MChipItemReq(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof MChipItemReq;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<MChipItemReq> {

    public Builder() {
    }

    public Builder(MChipItemReq message) {
      super(message);
    }

    @Override
    public MChipItemReq build() {
      return new MChipItemReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
