// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum MessageImageType
    implements ProtoEnum {
  MessageImageTypeImage(0),
  MessageImageTypeGif(1);

  private final int value;

  private MessageImageType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int MessageImageTypeImage_VALUE = 0;
  public static final int MessageImageTypeGif_VALUE = 1;

  public static MessageImageType valueOf(int value) {
    switch (value)  {
      case 0: return MessageImageTypeImage;
      case 1: return MessageImageTypeGif;
      default: return null;
    }
  }
}
