// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum MessageEventType
    implements ProtoEnum {
  MessageEventTypeNone(0);

  private final int value;

  private MessageEventType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int MessageEventTypeNone_VALUE = 0;

  public static MessageEventType valueOf(int value) {
    switch (value)  {
      case 0: return MessageEventTypeNone;
      default: return null;
    }
  }
}
