// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum MessageContentType
    implements ProtoEnum {
  MessageContentTypeTxt(0),
  MessageContentTypeImg(1),
  MessageContentTypeVoice(2),
  MessageContentTypeVideo(3),
  MessageContentTypePub(4),
  MessageContentTypeHtml(7),
  MessageContentTypeAd(8),
  MessageContectTypeDestroyLiveRoom(9);

  private final int value;

  private MessageContentType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int MessageContentTypeTxt_VALUE = 0;
  public static final int MessageContentTypeImg_VALUE = 1;
  public static final int MessageContentTypeVoice_VALUE = 2;
  public static final int MessageContentTypeVideo_VALUE = 3;
  public static final int MessageContentTypePub_VALUE = 4;
  public static final int MessageContentTypeHtml_VALUE = 7;
  public static final int MessageContentTypeAd_VALUE = 8;
  public static final int MessageContectTypeDestroyLiveRoom_VALUE = 9;

  public static MessageContentType valueOf(int value) {
    switch (value)  {
      case 0: return MessageContentTypeTxt;
      case 1: return MessageContentTypeImg;
      case 2: return MessageContentTypeVoice;
      case 3: return MessageContentTypeVideo;
      case 4: return MessageContentTypePub;
      case 7: return MessageContentTypeHtml;
      case 8: return MessageContentTypeAd;
      case 9: return MessageContectTypeDestroyLiveRoom;
      default: return null;
    }
  }
}
