// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class MGoldChangeRecord extends Message {

  public static final String DEFAULT_TITLE = "";
  public static final String DEFAULT_CONTENT = "";
  public static final Long DEFAULT_CHANGE = 0L;
  public static final Long DEFAULT_THETIME = 0L;

  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String title;

  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String content;

  @ProtoField(tag = 3, type = INT64, label = REQUIRED)
  public final Long change;

  @ProtoField(tag = 4, type = INT64, label = REQUIRED)
  public final Long theTime;

  private MGoldChangeRecord(Builder builder) {
    this.title = builder.title;
    this.content = builder.content;
    this.change = builder.change;
    this.theTime = builder.theTime;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MGoldChangeRecord)) return false;
    MGoldChangeRecord o = (MGoldChangeRecord) other;
    return equals(title, o.title)
        && equals(content, o.content)
        && equals(change, o.change)
        && equals(theTime, o.theTime);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = title != null ? title.hashCode() : 0;
      result = result * 37 + (content != null ? content.hashCode() : 0);
      result = result * 37 + (change != null ? change.hashCode() : 0);
      result = result * 37 + (theTime != null ? theTime.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<MGoldChangeRecord> {

    public String title;
    public String content;
    public Long change;
    public Long theTime;

    public Builder() {
    }

    public Builder(MGoldChangeRecord message) {
      super(message);
      if (message == null) return;
      this.title = message.title;
      this.content = message.content;
      this.change = message.change;
      this.theTime = message.theTime;
    }

    public Builder title(String title) {
      this.title = title;
      return this;
    }

    public Builder content(String content) {
      this.content = content;
      return this;
    }

    public Builder change(Long change) {
      this.change = change;
      return this;
    }

    public Builder theTime(Long theTime) {
      this.theTime = theTime;
      return this;
    }

    @Override
    public MGoldChangeRecord build() {
      checkRequiredFields();
      return new MGoldChangeRecord(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
