// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class MmsReportCmdRes extends Message {

  public static final Integer DEFAULT_CODE = 0;
  public static final String DEFAULT_MSG = "";

  @ProtoField(tag = 1, type = INT32)
  public final Integer code;

  @ProtoField(tag = 2, type = STRING)
  public final String msg;

  private MmsReportCmdRes(Builder builder) {
    this.code = builder.code;
    this.msg = builder.msg;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MmsReportCmdRes)) return false;
    MmsReportCmdRes o = (MmsReportCmdRes) other;
    return equals(code, o.code)
        && equals(msg, o.msg);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = code != null ? code.hashCode() : 0;
      result = result * 37 + (msg != null ? msg.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<MmsReportCmdRes> {

    public Integer code;
    public String msg;

    public Builder() {
    }

    public Builder(MmsReportCmdRes message) {
      super(message);
      if (message == null) return;
      this.code = message.code;
      this.msg = message.msg;
    }

    public Builder code(Integer code) {
      this.code = code;
      return this;
    }

    public Builder msg(String msg) {
      this.msg = msg;
      return this;
    }

    @Override
    public MmsReportCmdRes build() {
      return new MmsReportCmdRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
