// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class MonthLoveValReq extends Message {

  public static final List<Long> DEFAULT_UID = Collections.emptyList();
  public static final Integer DEFAULT_MONTH = 0;

  @ProtoField(tag = 1, type = UINT64, label = REPEATED)
  public final List<Long> uid;

  @ProtoField(tag = 2, type = UINT32, label = REQUIRED)
  public final Integer month;

  private MonthLoveValReq(Builder builder) {
    this.uid = immutableCopyOf(builder.uid);
    this.month = builder.month;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MonthLoveValReq)) return false;
    MonthLoveValReq o = (MonthLoveValReq) other;
    return equals(uid, o.uid)
        && equals(month, o.month);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uid != null ? uid.hashCode() : 1;
      result = result * 37 + (month != null ? month.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<MonthLoveValReq> {

    public List<Long> uid;
    public Integer month;

    public Builder() {
    }

    public Builder(MonthLoveValReq message) {
      super(message);
      if (message == null) return;
      this.uid = copyOf(message.uid);
      this.month = message.month;
    }

    public Builder uid(List<Long> uid) {
      this.uid = checkForNulls(uid);
      return this;
    }

    public Builder month(Integer month) {
      this.month = month;
      return this;
    }

    @Override
    public MonthLoveValReq build() {
      checkRequiredFields();
      return new MonthLoveValReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
