// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum MsgPushType
    implements ProtoEnum {
  PPushUserMsgUpdate(1),
  /**
   * 好友消息
   */
  PPushGroupListUpdate(4),
  /**
   * 群列表
   */
  PPushGroupMemberUpdate(16),
  /**
   * 群成员
   */
  PPushGroupMsgUpdate(32),
  /**
   * 群消息，GroupMsg
   */
  PPushGroupAppUpdate(64),
  /**
   * 消息补丁
   * < 256的是持久化消息
   * ==============================
   */
  PPushWebSessionUpdate(4096),
  PPushGroupRealTimeMsg(8192),
  /**
   * 实时群消息推送，GroupMsg
   */
  PPushGroupGiftRealTimeMsg(8193),
  /**
   * 实时群礼物消息推送，GiftMsgPush
   */
  PPushGroupLikeRealTimeMsg(8194),
  /**
   * 点赞消息，LikeMsgPush
   */
  PPushGroupMemberList(8196),
  /**
   * 成员消息
   */
  PPushGroupGiftDrawMsg(8197),
  /**
   * 实时群手绘礼物消息推送，GiftDrawMsgPush
   */
  PPushUserRealTimeMsg(8448),
  /**
   * 实时用户消息推送，UserMsg
   */
  PPushUserPromptMsg(8704),
  /**
   * 顶部提示，UserPromptMsg
   */
  PPushUserNoticeRealTimeMsg(9216),
  /**
   * 用户通知框，UserNotice
   */
  PPushChatMsg(9217),
  /**
   * 聊天推送，ChatMsgPush
   */
  PPushTexasQueueUpdate(17408),
  /**
   * 德州游戏，排队，TexasQueueUpdatePush
   */
  PPushTexasResult(17409),
  /**
   * 德州游戏，游戏结果，TexasResultPush
   */
  PPushTexasGameSeat(17410),
  /**
   * 游戏及座位推送，TexasGameSeatPush
   */
  PPushTexasRoomSetSpeak(17411),
  /**
   * 设置能否说话推送 TexasRoomSetSpeakPush
   */
  PPushWealthDrawBind(17665),
  /**
   * 提现绑定结果推送 WealthDrawBindPush
   */
  PPushLvUp(17666),
  /**
   * 升级推送 LvUpPush
   */
  PPushRedBag(17667),
  /**
   * 红包推送 RedBagPush
   */
  PPushLogUpdate(32768);

  private final int value;

  private MsgPushType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int PPushUserMsgUpdate_VALUE = 1;
  /**
   * 好友消息
   */
  public static final int PPushGroupListUpdate_VALUE = 4;
  /**
   * 群列表
   */
  public static final int PPushGroupMemberUpdate_VALUE = 16;
  /**
   * 群成员
   */
  public static final int PPushGroupMsgUpdate_VALUE = 32;
  /**
   * 群消息，GroupMsg
   */
  public static final int PPushGroupAppUpdate_VALUE = 64;
  /**
   * 消息补丁
   * < 256的是持久化消息
   * ==============================
   */
  public static final int PPushWebSessionUpdate_VALUE = 4096;
  public static final int PPushGroupRealTimeMsg_VALUE = 8192;
  /**
   * 实时群消息推送，GroupMsg
   */
  public static final int PPushGroupGiftRealTimeMsg_VALUE = 8193;
  /**
   * 实时群礼物消息推送，GiftMsgPush
   */
  public static final int PPushGroupLikeRealTimeMsg_VALUE = 8194;
  /**
   * 点赞消息，LikeMsgPush
   */
  public static final int PPushGroupMemberList_VALUE = 8196;
  /**
   * 成员消息
   */
  public static final int PPushGroupGiftDrawMsg_VALUE = 8197;
  /**
   * 实时群手绘礼物消息推送，GiftDrawMsgPush
   */
  public static final int PPushUserRealTimeMsg_VALUE = 8448;
  /**
   * 实时用户消息推送，UserMsg
   */
  public static final int PPushUserPromptMsg_VALUE = 8704;
  /**
   * 顶部提示，UserPromptMsg
   */
  public static final int PPushUserNoticeRealTimeMsg_VALUE = 9216;
  /**
   * 用户通知框，UserNotice
   */
  public static final int PPushChatMsg_VALUE = 9217;
  /**
   * 聊天推送，ChatMsgPush
   */
  public static final int PPushTexasQueueUpdate_VALUE = 17408;
  /**
   * 德州游戏，排队，TexasQueueUpdatePush
   */
  public static final int PPushTexasResult_VALUE = 17409;
  /**
   * 德州游戏，游戏结果，TexasResultPush
   */
  public static final int PPushTexasGameSeat_VALUE = 17410;
  /**
   * 游戏及座位推送，TexasGameSeatPush
   */
  public static final int PPushTexasRoomSetSpeak_VALUE = 17411;
  /**
   * 设置能否说话推送 TexasRoomSetSpeakPush
   */
  public static final int PPushWealthDrawBind_VALUE = 17665;
  /**
   * 提现绑定结果推送 WealthDrawBindPush
   */
  public static final int PPushLvUp_VALUE = 17666;
  /**
   * 升级推送 LvUpPush
   */
  public static final int PPushRedBag_VALUE = 17667;
  /**
   * 红包推送 RedBagPush
   */
  public static final int PPushLogUpdate_VALUE = 32768;

  public static MsgPushType valueOf(int value) {
    switch (value)  {
      case 1: return PPushUserMsgUpdate;
      case 4: return PPushGroupListUpdate;
      case 16: return PPushGroupMemberUpdate;
      case 32: return PPushGroupMsgUpdate;
      case 64: return PPushGroupAppUpdate;
      case 4096: return PPushWebSessionUpdate;
      case 8192: return PPushGroupRealTimeMsg;
      case 8193: return PPushGroupGiftRealTimeMsg;
      case 8194: return PPushGroupLikeRealTimeMsg;
      case 8196: return PPushGroupMemberList;
      case 8197: return PPushGroupGiftDrawMsg;
      case 8448: return PPushUserRealTimeMsg;
      case 8704: return PPushUserPromptMsg;
      case 9216: return PPushUserNoticeRealTimeMsg;
      case 9217: return PPushChatMsg;
      case 17408: return PPushTexasQueueUpdate;
      case 17409: return PPushTexasResult;
      case 17410: return PPushTexasGameSeat;
      case 17411: return PPushTexasRoomSetSpeak;
      case 17665: return PPushWealthDrawBind;
      case 17666: return PPushLvUp;
      case 17667: return PPushRedBag;
      case 32768: return PPushLogUpdate;
      default: return null;
    }
  }
}
