// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class MsgPush extends Message {

  public static final MsgPushType DEFAULT_PUSHTYPE = MsgPushType.PPushUserMsgUpdate;
  public static final Long DEFAULT_REVISION = 0L;
  public static final Long DEFAULT_GID = 0L;
  public static final Long DEFAULT_PARENTGID = 0L;
  public static final Long DEFAULT_UID = 0L;
  public static final Long DEFAULT_PEERUID = 0L;

  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final MsgPushType pushtype;

  @ProtoField(tag = 2, type = UINT64, label = REQUIRED)
  public final Long revision;

  @ProtoField(tag = 3, type = UINT64)
  public final Long gid;

  @ProtoField(tag = 4, type = UINT64)
  public final Long parentgid;

  @ProtoField(tag = 5, type = UINT64)
  public final Long uid;

  @ProtoField(tag = 6, type = UINT64)
  public final Long peeruid;

  private MsgPush(Builder builder) {
    this.pushtype = builder.pushtype;
    this.revision = builder.revision;
    this.gid = builder.gid;
    this.parentgid = builder.parentgid;
    this.uid = builder.uid;
    this.peeruid = builder.peeruid;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MsgPush)) return false;
    MsgPush o = (MsgPush) other;
    return equals(pushtype, o.pushtype)
        && equals(revision, o.revision)
        && equals(gid, o.gid)
        && equals(parentgid, o.parentgid)
        && equals(uid, o.uid)
        && equals(peeruid, o.peeruid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = pushtype != null ? pushtype.hashCode() : 0;
      result = result * 37 + (revision != null ? revision.hashCode() : 0);
      result = result * 37 + (gid != null ? gid.hashCode() : 0);
      result = result * 37 + (parentgid != null ? parentgid.hashCode() : 0);
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      result = result * 37 + (peeruid != null ? peeruid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<MsgPush> {

    public MsgPushType pushtype;
    public Long revision;
    public Long gid;
    public Long parentgid;
    public Long uid;
    public Long peeruid;

    public Builder() {
    }

    public Builder(MsgPush message) {
      super(message);
      if (message == null) return;
      this.pushtype = message.pushtype;
      this.revision = message.revision;
      this.gid = message.gid;
      this.parentgid = message.parentgid;
      this.uid = message.uid;
      this.peeruid = message.peeruid;
    }

    public Builder pushtype(MsgPushType pushtype) {
      this.pushtype = pushtype;
      return this;
    }

    public Builder revision(Long revision) {
      this.revision = revision;
      return this;
    }

    public Builder gid(Long gid) {
      this.gid = gid;
      return this;
    }

    public Builder parentgid(Long parentgid) {
      this.parentgid = parentgid;
      return this;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder peeruid(Long peeruid) {
      this.peeruid = peeruid;
      return this;
    }

    @Override
    public MsgPush build() {
      checkRequiredFields();
      return new MsgPush(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
