// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum ProtoVersion
    implements ProtoEnum {
  ProtoVersion_None(0),
  ProtoVersion_Current(1);

  private final int value;

  private ProtoVersion(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int ProtoVersion_None_VALUE = 0;
  public static final int ProtoVersion_Current_VALUE = 1;

  public static ProtoVersion valueOf(int value) {
    switch (value)  {
      case 0: return ProtoVersion_None;
      case 1: return ProtoVersion_Current;
      default: return null;
    }
  }
}
