// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class QueryRootReq extends Message {

  private QueryRootReq(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof QueryRootReq;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<QueryRootReq> {

    public Builder() {
    }

    public Builder(QueryRootReq message) {
      super(message);
    }

    @Override
    public QueryRootReq build() {
      return new QueryRootReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
