// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 读取消息
 */
public final class ReadMsgReq extends Message {

  public static final Long DEFAULT_FROMUID = 0L;
  public static final Long DEFAULT_MSGID = 0L;
  public static final Integer DEFAULT_READNUM = 0;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long fromUid;

  @ProtoField(tag = 2, type = UINT64)
  public final Long msgId;

  @ProtoField(tag = 3, type = UINT32)
  public final Integer readNum;

  private ReadMsgReq(Builder builder) {
    this.fromUid = builder.fromUid;
    this.msgId = builder.msgId;
    this.readNum = builder.readNum;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReadMsgReq)) return false;
    ReadMsgReq o = (ReadMsgReq) other;
    return equals(fromUid, o.fromUid)
        && equals(msgId, o.msgId)
        && equals(readNum, o.readNum);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = fromUid != null ? fromUid.hashCode() : 0;
      result = result * 37 + (msgId != null ? msgId.hashCode() : 0);
      result = result * 37 + (readNum != null ? readNum.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ReadMsgReq> {

    public Long fromUid;
    public Long msgId;
    public Integer readNum;

    public Builder() {
    }

    public Builder(ReadMsgReq message) {
      super(message);
      if (message == null) return;
      this.fromUid = message.fromUid;
      this.msgId = message.msgId;
      this.readNum = message.readNum;
    }

    public Builder fromUid(Long fromUid) {
      this.fromUid = fromUid;
      return this;
    }

    public Builder msgId(Long msgId) {
      this.msgId = msgId;
      return this;
    }

    public Builder readNum(Integer readNum) {
      this.readNum = readNum;
      return this;
    }

    @Override
    public ReadMsgReq build() {
      checkRequiredFields();
      return new ReadMsgReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
