// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class RechargeFeedbackRes extends Message {

  public static final Long DEFAULT_ORDERID = 0L;
  public static final Long DEFAULT_MGOLD = 0L;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long orderid;

  @ProtoField(tag = 2, type = UINT64, label = REQUIRED)
  public final Long mGold;

  private RechargeFeedbackRes(Builder builder) {
    this.orderid = builder.orderid;
    this.mGold = builder.mGold;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RechargeFeedbackRes)) return false;
    RechargeFeedbackRes o = (RechargeFeedbackRes) other;
    return equals(orderid, o.orderid)
        && equals(mGold, o.mGold);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = orderid != null ? orderid.hashCode() : 0;
      result = result * 37 + (mGold != null ? mGold.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RechargeFeedbackRes> {

    public Long orderid;
    public Long mGold;

    public Builder() {
    }

    public Builder(RechargeFeedbackRes message) {
      super(message);
      if (message == null) return;
      this.orderid = message.orderid;
      this.mGold = message.mGold;
    }

    public Builder orderid(Long orderid) {
      this.orderid = orderid;
      return this;
    }

    public Builder mGold(Long mGold) {
      this.mGold = mGold;
      return this;
    }

    @Override
    public RechargeFeedbackRes build() {
      checkRequiredFields();
      return new RechargeFeedbackRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
