// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class RechargePayGateCallbackReq extends Message {

  public static final String DEFAULT_APPID = "";
  public static final String DEFAULT_SIGN = "";
  public static final String DEFAULT_PARAM = "";
  public static final String DEFAULT_DATA = "";

  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String appId;

  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String sign;

  @ProtoField(tag = 3, type = STRING)
  public final String param;

  @ProtoField(tag = 4, type = STRING)
  public final String data;

  private RechargePayGateCallbackReq(Builder builder) {
    this.appId = builder.appId;
    this.sign = builder.sign;
    this.param = builder.param;
    this.data = builder.data;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RechargePayGateCallbackReq)) return false;
    RechargePayGateCallbackReq o = (RechargePayGateCallbackReq) other;
    return equals(appId, o.appId)
        && equals(sign, o.sign)
        && equals(param, o.param)
        && equals(data, o.data);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = appId != null ? appId.hashCode() : 0;
      result = result * 37 + (sign != null ? sign.hashCode() : 0);
      result = result * 37 + (param != null ? param.hashCode() : 0);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RechargePayGateCallbackReq> {

    public String appId;
    public String sign;
    public String param;
    public String data;

    public Builder() {
    }

    public Builder(RechargePayGateCallbackReq message) {
      super(message);
      if (message == null) return;
      this.appId = message.appId;
      this.sign = message.sign;
      this.param = message.param;
      this.data = message.data;
    }

    public Builder appId(String appId) {
      this.appId = appId;
      return this;
    }

    public Builder sign(String sign) {
      this.sign = sign;
      return this;
    }

    public Builder param(String param) {
      this.param = param;
      return this;
    }

    public Builder data(String data) {
      this.data = data;
      return this;
    }

    @Override
    public RechargePayGateCallbackReq build() {
      checkRequiredFields();
      return new RechargePayGateCallbackReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
