// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum RechargeOrderState
    implements ProtoEnum {
  OrderStateNone(0),
  OrderStateClosed(1),
  OrderStatePayWait(2),
  OrderStatePaySuccess(3);

  private final int value;

  private RechargeOrderState(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int OrderStateNone_VALUE = 0;
  public static final int OrderStateClosed_VALUE = 1;
  public static final int OrderStatePayWait_VALUE = 2;
  public static final int OrderStatePaySuccess_VALUE = 3;

  public static RechargeOrderState valueOf(int value) {
    switch (value)  {
      case 0: return OrderStateNone;
      case 1: return OrderStateClosed;
      case 2: return OrderStatePayWait;
      case 3: return OrderStatePaySuccess;
      default: return null;
    }
  }
}
