// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class RedBagPush extends Message {

  public static final Long DEFAULT_BAGID = 0L;
  public static final String DEFAULT_BAGNAME = "";
  public static final Integer DEFAULT_GIFTID = 0;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long bagId;

  @ProtoField(tag = 2, label = REQUIRED)
  public final UserInfo userInfo;

  @ProtoField(tag = 3, type = STRING)
  public final String bagName;

  @ProtoField(tag = 4, type = UINT32)
  public final Integer giftId;

  private RedBagPush(Builder builder) {
    this.bagId = builder.bagId;
    this.userInfo = builder.userInfo;
    this.bagName = builder.bagName;
    this.giftId = builder.giftId;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RedBagPush)) return false;
    RedBagPush o = (RedBagPush) other;
    return equals(bagId, o.bagId)
        && equals(userInfo, o.userInfo)
        && equals(bagName, o.bagName)
        && equals(giftId, o.giftId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = bagId != null ? bagId.hashCode() : 0;
      result = result * 37 + (userInfo != null ? userInfo.hashCode() : 0);
      result = result * 37 + (bagName != null ? bagName.hashCode() : 0);
      result = result * 37 + (giftId != null ? giftId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RedBagPush> {

    public Long bagId;
    public UserInfo userInfo;
    public String bagName;
    public Integer giftId;

    public Builder() {
    }

    public Builder(RedBagPush message) {
      super(message);
      if (message == null) return;
      this.bagId = message.bagId;
      this.userInfo = message.userInfo;
      this.bagName = message.bagName;
      this.giftId = message.giftId;
    }

    public Builder bagId(Long bagId) {
      this.bagId = bagId;
      return this;
    }

    public Builder userInfo(UserInfo userInfo) {
      this.userInfo = userInfo;
      return this;
    }

    public Builder bagName(String bagName) {
      this.bagName = bagName;
      return this;
    }

    public Builder giftId(Integer giftId) {
      this.giftId = giftId;
      return this;
    }

    @Override
    public RedBagPush build() {
      checkRequiredFields();
      return new RedBagPush(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
