// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class ReportLogSetRes extends Message {

  private ReportLogSetRes(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof ReportLogSetRes;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<ReportLogSetRes> {

    public Builder() {
    }

    public Builder(ReportLogSetRes message) {
      super(message);
    }

    @Override
    public ReportLogSetRes build() {
      return new ReportLogSetRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
