// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class ReportLogSetReq extends Message {

  public static final Long DEFAULT_UID = 0L;
  public static final Integer DEFAULT_LEVEL = 1;
  public static final String DEFAULT_EXPIRED = "";

  @ProtoField(tag = 1, type = UINT64)
  public final Long uid;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer level;

  @ProtoField(tag = 3, type = STRING)
  public final String expired;

  private ReportLogSetReq(Builder builder) {
    this.uid = builder.uid;
    this.level = builder.level;
    this.expired = builder.expired;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReportLogSetReq)) return false;
    ReportLogSetReq o = (ReportLogSetReq) other;
    return equals(uid, o.uid)
        && equals(level, o.level)
        && equals(expired, o.expired);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uid != null ? uid.hashCode() : 0;
      result = result * 37 + (level != null ? level.hashCode() : 0);
      result = result * 37 + (expired != null ? expired.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ReportLogSetReq> {

    public Long uid;
    public Integer level;
    public String expired;

    public Builder() {
    }

    public Builder(ReportLogSetReq message) {
      super(message);
      if (message == null) return;
      this.uid = message.uid;
      this.level = message.level;
      this.expired = message.expired;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder level(Integer level) {
      this.level = level;
      return this;
    }

    public Builder expired(String expired) {
      this.expired = expired;
      return this;
    }

    @Override
    public ReportLogSetReq build() {
      return new ReportLogSetReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
