// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class ReportLogRes extends Message {

  public static final String DEFAULT_REPORT = "";

  @ProtoField(tag = 1, type = STRING)
  public final String report;

  private ReportLogRes(Builder builder) {
    this.report = builder.report;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReportLogRes)) return false;
    return equals(report, ((ReportLogRes) other).report);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = report != null ? report.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<ReportLogRes> {

    public String report;

    public Builder() {
    }

    public Builder(ReportLogRes message) {
      super(message);
      if (message == null) return;
      this.report = message.report;
    }

    public Builder report(String report) {
      this.report = report;
      return this;
    }

    @Override
    public ReportLogRes build() {
      return new ReportLogRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
