// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class ReportLogItem extends Message {

  public static final String DEFAULT_REPORT = "";
  public static final String DEFAULT_CREATETIME = "";

  @ProtoField(tag = 1, type = STRING)
  public final String Report;

  @ProtoField(tag = 2, type = STRING)
  public final String CreateTime;

  private ReportLogItem(Builder builder) {
    this.Report = builder.Report;
    this.CreateTime = builder.CreateTime;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReportLogItem)) return false;
    ReportLogItem o = (ReportLogItem) other;
    return equals(Report, o.Report)
        && equals(CreateTime, o.CreateTime);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = Report != null ? Report.hashCode() : 0;
      result = result * 37 + (CreateTime != null ? CreateTime.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ReportLogItem> {

    public String Report;
    public String CreateTime;

    public Builder() {
    }

    public Builder(ReportLogItem message) {
      super(message);
      if (message == null) return;
      this.Report = message.Report;
      this.CreateTime = message.CreateTime;
    }

    public Builder Report(String Report) {
      this.Report = Report;
      return this;
    }

    public Builder CreateTime(String CreateTime) {
      this.CreateTime = CreateTime;
      return this;
    }

    @Override
    public ReportLogItem build() {
      return new ReportLogItem(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
