// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class RoomLabelRank extends Message {

  public static final Long DEFAULT_UID = 0L;
  public static final String DEFAULT_NAME = "";
  public static final String DEFAULT_VAL = "";

  @ProtoField(tag = 1, type = UINT64)
  public final Long uid;

  @ProtoField(tag = 2, type = STRING)
  public final String name;

  @ProtoField(tag = 3, type = STRING)
  public final String val;

  private RoomLabelRank(Builder builder) {
    this.uid = builder.uid;
    this.name = builder.name;
    this.val = builder.val;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RoomLabelRank)) return false;
    RoomLabelRank o = (RoomLabelRank) other;
    return equals(uid, o.uid)
        && equals(name, o.name)
        && equals(val, o.val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uid != null ? uid.hashCode() : 0;
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (val != null ? val.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RoomLabelRank> {

    public Long uid;
    public String name;
    public String val;

    public Builder() {
    }

    public Builder(RoomLabelRank message) {
      super(message);
      if (message == null) return;
      this.uid = message.uid;
      this.name = message.name;
      this.val = message.val;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder val(String val) {
      this.val = val;
      return this;
    }

    @Override
    public RoomLabelRank build() {
      return new RoomLabelRank(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
