// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum RootType
    implements ProtoEnum {
  RootAdmin(4096),
  /**
   * 管理员
   */
  RootLogin(1),
  /**
   * 登录权限
   */
  RootChangeMGold(2),
  /**
   * 修改m币权限
   */
  RootChangeMBean(4),
  /**
   * 修改m豆权限
   */
  RootChangeMChip(8),
  /**
   * 修改筹码权限
   */
  RootSetCards(16),
  /**
   * 设置牌局权限
   */
  RootUserSort(32),
  /**
   * 修改用户信息
   */
  RootAd(64),
  /**
   * 修改广告
   */
  RootMatch(128),
  /**
   * 比赛配置
   */
  RootYYMoney(256);

  private final int value;

  private RootType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int RootAdmin_VALUE = 4096;
  /**
   * 管理员
   */
  public static final int RootLogin_VALUE = 1;
  /**
   * 登录权限
   */
  public static final int RootChangeMGold_VALUE = 2;
  /**
   * 修改m币权限
   */
  public static final int RootChangeMBean_VALUE = 4;
  /**
   * 修改m豆权限
   */
  public static final int RootChangeMChip_VALUE = 8;
  /**
   * 修改筹码权限
   */
  public static final int RootSetCards_VALUE = 16;
  /**
   * 设置牌局权限
   */
  public static final int RootUserSort_VALUE = 32;
  /**
   * 修改用户信息
   */
  public static final int RootAd_VALUE = 64;
  /**
   * 修改广告
   */
  public static final int RootMatch_VALUE = 128;
  /**
   * 比赛配置
   */
  public static final int RootYYMoney_VALUE = 256;

  public static RootType valueOf(int value) {
    switch (value)  {
      case 4096: return RootAdmin;
      case 1: return RootLogin;
      case 2: return RootChangeMGold;
      case 4: return RootChangeMBean;
      case 8: return RootChangeMChip;
      case 16: return RootSetCards;
      case 32: return RootUserSort;
      case 64: return RootAd;
      case 128: return RootMatch;
      case 256: return RootYYMoney;
      default: return null;
    }
  }
}
