// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class SessionResumeRes extends Message {

  private SessionResumeRes(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof SessionResumeRes;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<SessionResumeRes> {

    public Builder() {
    }

    public Builder(SessionResumeRes message) {
      super(message);
    }

    @Override
    public SessionResumeRes build() {
      return new SessionResumeRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
