// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

public final class SessionSuspendRes extends Message {

  public static final Boolean DEFAULT_SUSPEND = false;

  @ProtoField(tag = 1, type = BOOL)
  public final Boolean suspend;

  private SessionSuspendRes(Builder builder) {
    this.suspend = builder.suspend;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SessionSuspendRes)) return false;
    return equals(suspend, ((SessionSuspendRes) other).suspend);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = suspend != null ? suspend.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<SessionSuspendRes> {

    public Boolean suspend;

    public Builder() {
    }

    public Builder(SessionSuspendRes message) {
      super(message);
      if (message == null) return;
      this.suspend = message.suspend;
    }

    public Builder suspend(Boolean suspend) {
      this.suspend = suspend;
      return this;
    }

    @Override
    public SessionSuspendRes build() {
      return new SessionSuspendRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
