// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

/**
 * 会话挂起请求
 */
public final class SessionSuspendReq extends Message {

  public static final Boolean DEFAULT_SUSPEND = false;

  @ProtoField(tag = 1, type = BOOL)
  public final Boolean suspend;

  private SessionSuspendReq(Builder builder) {
    this.suspend = builder.suspend;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SessionSuspendReq)) return false;
    return equals(suspend, ((SessionSuspendReq) other).suspend);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = suspend != null ? suspend.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<SessionSuspendReq> {

    public Boolean suspend;

    public Builder() {
    }

    public Builder(SessionSuspendReq message) {
      super(message);
      if (message == null) return;
      this.suspend = message.suspend;
    }

    public Builder suspend(Boolean suspend) {
      this.suspend = suspend;
      return this;
    }

    @Override
    public SessionSuspendReq build() {
      return new SessionSuspendReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
