// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class SetActArgsRes extends Message {

  private SetActArgsRes(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof SetActArgsRes;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<SetActArgsRes> {

    public Builder() {
    }

    public Builder(SetActArgsRes message) {
      super(message);
    }

    @Override
    public SetActArgsRes build() {
      return new SetActArgsRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
