// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class SetRootReq extends Message {

  public static final List<UserRoot> DEFAULT_USERS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<UserRoot> users;

  private SetRootReq(Builder builder) {
    this.users = immutableCopyOf(builder.users);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SetRootReq)) return false;
    return equals(users, ((SetRootReq) other).users);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = users != null ? users.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<SetRootReq> {

    public List<UserRoot> users;

    public Builder() {
    }

    public Builder(SetRootReq message) {
      super(message);
      if (message == null) return;
      this.users = copyOf(message.users);
    }

    public Builder users(List<UserRoot> users) {
      this.users = checkForNulls(users);
      return this;
    }

    @Override
    public SetRootReq build() {
      return new SetRootReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
