// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum SPActivity
    implements ProtoEnum {
  PWinChipRankReq(1),
  PWinChipRankRes(2),
  PSetActArgsReq(3),
  PSetActArgsRes(4),
  PYYBabyPromotionReq(17),
  PYYBabyPromotionRes(18),
  PYYBindReq(19),
  PYYBindRes(20);

  private final int value;

  private SPActivity(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int PWinChipRankReq_VALUE = 1;
  public static final int PWinChipRankRes_VALUE = 2;
  public static final int PSetActArgsReq_VALUE = 3;
  public static final int PSetActArgsRes_VALUE = 4;
  public static final int PYYBabyPromotionReq_VALUE = 17;
  public static final int PYYBabyPromotionRes_VALUE = 18;
  public static final int PYYBindReq_VALUE = 19;
  public static final int PYYBindRes_VALUE = 20;

  public static SPActivity valueOf(int value) {
    switch (value)  {
      case 1: return PWinChipRankReq;
      case 2: return PWinChipRankRes;
      case 3: return PSetActArgsReq;
      case 4: return PSetActArgsRes;
      case 17: return PYYBabyPromotionReq;
      case 18: return PYYBabyPromotionRes;
      case 19: return PYYBindReq;
      case 20: return PYYBindRes;
      default: return null;
    }
  }
}
