// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum SPConfig
    implements ProtoEnum {
  PConfigJsonReq(1),
  PConfigJsonRes(2),
  PConfigJsonListReq(3),
  PConfigJsonListRes(4),
  PSysConfReq(5),
  PSysConfRes(6);

  private final int value;

  private SPConfig(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int PConfigJsonReq_VALUE = 1;
  public static final int PConfigJsonRes_VALUE = 2;
  public static final int PConfigJsonListReq_VALUE = 3;
  public static final int PConfigJsonListRes_VALUE = 4;
  public static final int PSysConfReq_VALUE = 5;
  public static final int PSysConfRes_VALUE = 6;

  public static SPConfig valueOf(int value) {
    switch (value)  {
      case 1: return PConfigJsonReq;
      case 2: return PConfigJsonRes;
      case 3: return PConfigJsonListReq;
      case 4: return PConfigJsonListRes;
      case 5: return PSysConfReq;
      case 6: return PSysConfRes;
      default: return null;
    }
  }
}
