// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum SPGroupMsg
    implements ProtoEnum {
  PGroupMsgSendReq(0),
  PGroupMsgSendRes(1),
  PGroupMsgListReq(2),
  PGroupMsgListRes(3),
  PGroupMsgSearchReq(16),
  PGroupMsgSearchRes(17);

  private final int value;

  private SPGroupMsg(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int PGroupMsgSendReq_VALUE = 0;
  public static final int PGroupMsgSendRes_VALUE = 1;
  public static final int PGroupMsgListReq_VALUE = 2;
  public static final int PGroupMsgListRes_VALUE = 3;
  public static final int PGroupMsgSearchReq_VALUE = 16;
  public static final int PGroupMsgSearchRes_VALUE = 17;

  public static SPGroupMsg valueOf(int value) {
    switch (value)  {
      case 0: return PGroupMsgSendReq;
      case 1: return PGroupMsgSendRes;
      case 2: return PGroupMsgListReq;
      case 3: return PGroupMsgListRes;
      case 16: return PGroupMsgSearchReq;
      case 17: return PGroupMsgSearchRes;
      default: return null;
    }
  }
}
