// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum SPGroup
    implements ProtoEnum {
  PGroupCreateReq(0),
  PGroupCreateRes(1),
  PGroupJoinReq(2),
  PGroupJoinRes(3),
  PGroupQuitReq(4),
  PGroupQuitRes(5),
  PGroupInfoReq(6),
  PGroupInfoRes(7),
  PGroupInfoModifyReq(8),
  PGroupInfoModifyRes(9),
  PGroupDestroyReq(10),
  PGroupDestroyRes(11),
  PGroupLiveHeartReq(12),
  PGroupLiveHeartRes(13),
  PGroupListReq(16),
  PGroupListRes(17),
  PGroupSearchReq(32),
  PGroupSearchRes(33),
  PGroupMapReq(34),
  PGroupMapRes(35),
  PGroupBetsReq(48),
  PGroupBetsRes(49);

  private final int value;

  private SPGroup(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int PGroupCreateReq_VALUE = 0;
  public static final int PGroupCreateRes_VALUE = 1;
  public static final int PGroupJoinReq_VALUE = 2;
  public static final int PGroupJoinRes_VALUE = 3;
  public static final int PGroupQuitReq_VALUE = 4;
  public static final int PGroupQuitRes_VALUE = 5;
  public static final int PGroupInfoReq_VALUE = 6;
  public static final int PGroupInfoRes_VALUE = 7;
  public static final int PGroupInfoModifyReq_VALUE = 8;
  public static final int PGroupInfoModifyRes_VALUE = 9;
  public static final int PGroupDestroyReq_VALUE = 10;
  public static final int PGroupDestroyRes_VALUE = 11;
  public static final int PGroupLiveHeartReq_VALUE = 12;
  public static final int PGroupLiveHeartRes_VALUE = 13;
  public static final int PGroupListReq_VALUE = 16;
  public static final int PGroupListRes_VALUE = 17;
  public static final int PGroupSearchReq_VALUE = 32;
  public static final int PGroupSearchRes_VALUE = 33;
  public static final int PGroupMapReq_VALUE = 34;
  public static final int PGroupMapRes_VALUE = 35;
  public static final int PGroupBetsReq_VALUE = 48;
  public static final int PGroupBetsRes_VALUE = 49;

  public static SPGroup valueOf(int value) {
    switch (value)  {
      case 0: return PGroupCreateReq;
      case 1: return PGroupCreateRes;
      case 2: return PGroupJoinReq;
      case 3: return PGroupJoinRes;
      case 4: return PGroupQuitReq;
      case 5: return PGroupQuitRes;
      case 6: return PGroupInfoReq;
      case 7: return PGroupInfoRes;
      case 8: return PGroupInfoModifyReq;
      case 9: return PGroupInfoModifyRes;
      case 10: return PGroupDestroyReq;
      case 11: return PGroupDestroyRes;
      case 12: return PGroupLiveHeartReq;
      case 13: return PGroupLiveHeartRes;
      case 16: return PGroupListReq;
      case 17: return PGroupListRes;
      case 32: return PGroupSearchReq;
      case 33: return PGroupSearchRes;
      case 34: return PGroupMapReq;
      case 35: return PGroupMapRes;
      case 48: return PGroupBetsReq;
      case 49: return PGroupBetsRes;
      default: return null;
    }
  }
}
