// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class SubscribeRes extends Message {

  public static final Long DEFAULT_UID = 0L;
  public static final Boolean DEFAULT_SUBSCRIBE = false;

  @ProtoField(tag = 1, type = UINT64)
  public final Long uid;

  @ProtoField(tag = 2, type = BOOL)
  public final Boolean subscribe;

  private SubscribeRes(Builder builder) {
    this.uid = builder.uid;
    this.subscribe = builder.subscribe;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SubscribeRes)) return false;
    SubscribeRes o = (SubscribeRes) other;
    return equals(uid, o.uid)
        && equals(subscribe, o.subscribe);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uid != null ? uid.hashCode() : 0;
      result = result * 37 + (subscribe != null ? subscribe.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SubscribeRes> {

    public Long uid;
    public Boolean subscribe;

    public Builder() {
    }

    public Builder(SubscribeRes message) {
      super(message);
      if (message == null) return;
      this.uid = message.uid;
      this.subscribe = message.subscribe;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder subscribe(Boolean subscribe) {
      this.subscribe = subscribe;
      return this;
    }

    @Override
    public SubscribeRes build() {
      return new SubscribeRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
