// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

/**
 * 取消排队
 */
public final class TexasQueueQuitReq extends Message {

  private TexasQueueQuitReq(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof TexasQueueQuitReq;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<TexasQueueQuitReq> {

    public Builder() {
    }

    public Builder(TexasQueueQuitReq message) {
      super(message);
    }

    @Override
    public TexasQueueQuitReq build() {
      return new TexasQueueQuitReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
