// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class TexasRoomSetSpeakRes extends Message {

  private TexasRoomSetSpeakRes(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof TexasRoomSetSpeakRes;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<TexasRoomSetSpeakRes> {

    public Builder() {
    }

    public Builder(TexasRoomSetSpeakRes message) {
      super(message);
    }

    @Override
    public TexasRoomSetSpeakRes build() {
      return new TexasRoomSetSpeakRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
