// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class TexasQueueQueryReq extends Message {

  private TexasQueueQueryReq(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof TexasQueueQueryReq;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<TexasQueueQueryReq> {

    public Builder() {
    }

    public Builder(TexasQueueQueryReq message) {
      super(message);
    }

    @Override
    public TexasQueueQueryReq build() {
      return new TexasQueueQueryReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
