// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class TexasMyReadyRes extends Message {

  private TexasMyReadyRes(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof TexasMyReadyRes;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<TexasMyReadyRes> {

    public Builder() {
    }

    public Builder(TexasMyReadyRes message) {
      super(message);
    }

    @Override
    public TexasMyReadyRes build() {
      return new TexasMyReadyRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
