// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REPEATED;

public final class TexasMatchListRes extends Message {

  public static final Integer DEFAULT_INDEX = 0;
  public static final Integer DEFAULT_FETCHS = 0;
  public static final List<TexasMatchInfo> DEFAULT_ITEMS = Collections.emptyList();

  @ProtoField(tag = 1, type = UINT32)
  public final Integer index;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer fetchs;

  @ProtoField(tag = 9, label = REPEATED)
  public final List<TexasMatchInfo> items;

  private TexasMatchListRes(Builder builder) {
    this.index = builder.index;
    this.fetchs = builder.fetchs;
    this.items = immutableCopyOf(builder.items);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TexasMatchListRes)) return false;
    TexasMatchListRes o = (TexasMatchListRes) other;
    return equals(index, o.index)
        && equals(fetchs, o.fetchs)
        && equals(items, o.items);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = index != null ? index.hashCode() : 0;
      result = result * 37 + (fetchs != null ? fetchs.hashCode() : 0);
      result = result * 37 + (items != null ? items.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TexasMatchListRes> {

    public Integer index;
    public Integer fetchs;
    public List<TexasMatchInfo> items;

    public Builder() {
    }

    public Builder(TexasMatchListRes message) {
      super(message);
      if (message == null) return;
      this.index = message.index;
      this.fetchs = message.fetchs;
      this.items = copyOf(message.items);
    }

    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    public Builder fetchs(Integer fetchs) {
      this.fetchs = fetchs;
      return this;
    }

    public Builder items(List<TexasMatchInfo> items) {
      this.items = checkForNulls(items);
      return this;
    }

    @Override
    public TexasMatchListRes build() {
      return new TexasMatchListRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
