// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum TexasGameState
    implements ProtoEnum {
  TexasGame_NotStart(0),
  /**
   * 没开始
   */
  TexasGame_Preflop(1),
  /**
   * 翻牌前
   */
  TexasGame_Flop(2),
  /**
   * 翻牌
   */
  TexasGame_Turn(3),
  /**
   * 转牌
   */
  TexasGame_River(4),
  /**
   * 河牌
   */
  TexasGame_Over(5);

  private final int value;

  private TexasGameState(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int TexasGame_NotStart_VALUE = 0;
  /**
   * 没开始
   */
  public static final int TexasGame_Preflop_VALUE = 1;
  /**
   * 翻牌前
   */
  public static final int TexasGame_Flop_VALUE = 2;
  /**
   * 翻牌
   */
  public static final int TexasGame_Turn_VALUE = 3;
  /**
   * 转牌
   */
  public static final int TexasGame_River_VALUE = 4;
  /**
   * 河牌
   */
  public static final int TexasGame_Over_VALUE = 5;

  public static TexasGameState valueOf(int value) {
    switch (value)  {
      case 0: return TexasGame_NotStart;
      case 1: return TexasGame_Preflop;
      case 2: return TexasGame_Flop;
      case 3: return TexasGame_Turn;
      case 4: return TexasGame_River;
      case 5: return TexasGame_Over;
      default: return null;
    }
  }
}
