// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class TexasKickRes extends Message {

  private TexasKickRes(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof TexasKickRes;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<TexasKickRes> {

    public Builder() {
    }

    public Builder(TexasKickRes message) {
      super(message);
    }

    @Override
    public TexasKickRes build() {
      return new TexasKickRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
