// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 请求退出房间
 */
public final class TexasExitRoomReq extends Message {

  public static final Integer DEFAULT_REQ = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer req;

  private TexasExitRoomReq(Builder builder) {
    this.req = builder.req;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TexasExitRoomReq)) return false;
    return equals(req, ((TexasExitRoomReq) other).req);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = req != null ? req.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<TexasExitRoomReq> {

    public Integer req;

    public Builder() {
    }

    public Builder(TexasExitRoomReq message) {
      super(message);
      if (message == null) return;
      this.req = message.req;
    }

    public Builder req(Integer req) {
      this.req = req;
      return this;
    }

    @Override
    public TexasExitRoomReq build() {
      checkRequiredFields();
      return new TexasExitRoomReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
