// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;

/**
 * 报名列表
 */
public final class TexasMatchSignListReq extends Message {

  public static final Integer DEFAULT_ACTID = 0;

  @ProtoField(tag = 1, type = UINT32)
  public final Integer actId;

  private TexasMatchSignListReq(Builder builder) {
    this.actId = builder.actId;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TexasMatchSignListReq)) return false;
    return equals(actId, ((TexasMatchSignListReq) other).actId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = actId != null ? actId.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<TexasMatchSignListReq> {

    public Integer actId;

    public Builder() {
    }

    public Builder(TexasMatchSignListReq message) {
      super(message);
      if (message == null) return;
      this.actId = message.actId;
    }

    public Builder actId(Integer actId) {
      this.actId = actId;
      return this;
    }

    @Override
    public TexasMatchSignListReq build() {
      return new TexasMatchSignListReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
