// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class TexasSetRes extends Message {

  public static final Long DEFAULT_RES = 0L;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long res;

  private TexasSetRes(Builder builder) {
    this.res = builder.res;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TexasSetRes)) return false;
    return equals(res, ((TexasSetRes) other).res);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = res != null ? res.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<TexasSetRes> {

    public Long res;

    public Builder() {
    }

    public Builder(TexasSetRes message) {
      super(message);
      if (message == null) return;
      this.res = message.res;
    }

    public Builder res(Long res) {
      this.res = res;
      return this;
    }

    @Override
    public TexasSetRes build() {
      checkRequiredFields();
      return new TexasSetRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
