// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

public final class TexasMatchSetRes extends Message {

  @ProtoField(tag = 1)
  public final TexasMatchInfo info;

  private TexasMatchSetRes(Builder builder) {
    this.info = builder.info;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TexasMatchSetRes)) return false;
    return equals(info, ((TexasMatchSetRes) other).info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = info != null ? info.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<TexasMatchSetRes> {

    public TexasMatchInfo info;

    public Builder() {
    }

    public Builder(TexasMatchSetRes message) {
      super(message);
      if (message == null) return;
      this.info = message.info;
    }

    public Builder info(TexasMatchInfo info) {
      this.info = info;
      return this;
    }

    @Override
    public TexasMatchSetRes build() {
      return new TexasMatchSetRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
