// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum TexasSelect
    implements ProtoEnum {
  SELECT_FLOP(0),
  /**
   * 弃牌
   */
  SELECT_CHECK(1),
  /**
   * 过
   */
  SELECT_CALL(2),
  /**
   * 跟
   */
  SELECT_RAISE(3);

  private final int value;

  private TexasSelect(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int SELECT_FLOP_VALUE = 0;
  /**
   * 弃牌
   */
  public static final int SELECT_CHECK_VALUE = 1;
  /**
   * 过
   */
  public static final int SELECT_CALL_VALUE = 2;
  /**
   * 跟
   */
  public static final int SELECT_RAISE_VALUE = 3;

  public static TexasSelect valueOf(int value) {
    switch (value)  {
      case 0: return SELECT_FLOP;
      case 1: return SELECT_CHECK;
      case 2: return SELECT_CALL;
      case 3: return SELECT_RAISE;
      default: return null;
    }
  }
}
