// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class TexasPlayerWarRecordRes extends Message {

  public static final Integer DEFAULT_INDEX = 0;
  public static final Integer DEFAULT_FETCHS = 0;
  public static final Long DEFAULT_THEUID = 0L;
  public static final Long DEFAULT_TOTALTEXAS = 0L;
  public static final Long DEFAULT_PROFITLOSS = 0L;
  public static final List<TexasPlayerWarRecord> DEFAULT_RECORDS = Collections.emptyList();

  @ProtoField(tag = 1, type = UINT32)
  public final Integer index;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer fetchs;

  @ProtoField(tag = 3, type = UINT64)
  public final Long theUid;

  @ProtoField(tag = 4, type = UINT64, label = REQUIRED)
  public final Long totalTexas;

  @ProtoField(tag = 5, type = INT64, label = REQUIRED)
  public final Long profitLoss;

  @ProtoField(tag = 6, label = REPEATED)
  public final List<TexasPlayerWarRecord> records;

  private TexasPlayerWarRecordRes(Builder builder) {
    this.index = builder.index;
    this.fetchs = builder.fetchs;
    this.theUid = builder.theUid;
    this.totalTexas = builder.totalTexas;
    this.profitLoss = builder.profitLoss;
    this.records = immutableCopyOf(builder.records);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TexasPlayerWarRecordRes)) return false;
    TexasPlayerWarRecordRes o = (TexasPlayerWarRecordRes) other;
    return equals(index, o.index)
        && equals(fetchs, o.fetchs)
        && equals(theUid, o.theUid)
        && equals(totalTexas, o.totalTexas)
        && equals(profitLoss, o.profitLoss)
        && equals(records, o.records);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = index != null ? index.hashCode() : 0;
      result = result * 37 + (fetchs != null ? fetchs.hashCode() : 0);
      result = result * 37 + (theUid != null ? theUid.hashCode() : 0);
      result = result * 37 + (totalTexas != null ? totalTexas.hashCode() : 0);
      result = result * 37 + (profitLoss != null ? profitLoss.hashCode() : 0);
      result = result * 37 + (records != null ? records.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TexasPlayerWarRecordRes> {

    public Integer index;
    public Integer fetchs;
    public Long theUid;
    public Long totalTexas;
    public Long profitLoss;
    public List<TexasPlayerWarRecord> records;

    public Builder() {
    }

    public Builder(TexasPlayerWarRecordRes message) {
      super(message);
      if (message == null) return;
      this.index = message.index;
      this.fetchs = message.fetchs;
      this.theUid = message.theUid;
      this.totalTexas = message.totalTexas;
      this.profitLoss = message.profitLoss;
      this.records = copyOf(message.records);
    }

    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    public Builder fetchs(Integer fetchs) {
      this.fetchs = fetchs;
      return this;
    }

    public Builder theUid(Long theUid) {
      this.theUid = theUid;
      return this;
    }

    public Builder totalTexas(Long totalTexas) {
      this.totalTexas = totalTexas;
      return this;
    }

    public Builder profitLoss(Long profitLoss) {
      this.profitLoss = profitLoss;
      return this;
    }

    public Builder records(List<TexasPlayerWarRecord> records) {
      this.records = checkForNulls(records);
      return this;
    }

    @Override
    public TexasPlayerWarRecordRes build() {
      checkRequiredFields();
      return new TexasPlayerWarRecordRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
