// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class TexasJoinRes extends Message {

  public static final Integer DEFAULT_RES = 0;
  public static final Long DEFAULT_ROOMID = 0L;
  public static final Integer DEFAULT_SEAT = 0;
  public static final Integer DEFAULT_CANSPEAK = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer res;

  /**
   * 0加入成功1在其他牌局2加入失败
   */
  @ProtoField(tag = 2, type = UINT64, label = REQUIRED)
  public final Long roomId;

  @ProtoField(tag = 3, type = UINT32, label = REQUIRED)
  public final Integer seat;

  /**
   * 座位号
   */
  @ProtoField(tag = 4, type = UINT32)
  public final Integer canSpeak;

  private TexasJoinRes(Builder builder) {
    this.res = builder.res;
    this.roomId = builder.roomId;
    this.seat = builder.seat;
    this.canSpeak = builder.canSpeak;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TexasJoinRes)) return false;
    TexasJoinRes o = (TexasJoinRes) other;
    return equals(res, o.res)
        && equals(roomId, o.roomId)
        && equals(seat, o.seat)
        && equals(canSpeak, o.canSpeak);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = res != null ? res.hashCode() : 0;
      result = result * 37 + (roomId != null ? roomId.hashCode() : 0);
      result = result * 37 + (seat != null ? seat.hashCode() : 0);
      result = result * 37 + (canSpeak != null ? canSpeak.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TexasJoinRes> {

    public Integer res;
    public Long roomId;
    public Integer seat;
    public Integer canSpeak;

    public Builder() {
    }

    public Builder(TexasJoinRes message) {
      super(message);
      if (message == null) return;
      this.res = message.res;
      this.roomId = message.roomId;
      this.seat = message.seat;
      this.canSpeak = message.canSpeak;
    }

    public Builder res(Integer res) {
      this.res = res;
      return this;
    }

    /**
     * 0加入成功1在其他牌局2加入失败
     */
    public Builder roomId(Long roomId) {
      this.roomId = roomId;
      return this;
    }

    public Builder seat(Integer seat) {
      this.seat = seat;
      return this;
    }

    /**
     * 座位号
     */
    public Builder canSpeak(Integer canSpeak) {
      this.canSpeak = canSpeak;
      return this;
    }

    @Override
    public TexasJoinRes build() {
      checkRequiredFields();
      return new TexasJoinRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
