// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class UnreadMsgRes extends Message {

  public static final List<UnreadMsgId> DEFAULT_UNREADS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<UnreadMsgId> unreads;

  private UnreadMsgRes(Builder builder) {
    this.unreads = immutableCopyOf(builder.unreads);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UnreadMsgRes)) return false;
    return equals(unreads, ((UnreadMsgRes) other).unreads);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = unreads != null ? unreads.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<UnreadMsgRes> {

    public List<UnreadMsgId> unreads;

    public Builder() {
    }

    public Builder(UnreadMsgRes message) {
      super(message);
      if (message == null) return;
      this.unreads = copyOf(message.unreads);
    }

    public Builder unreads(List<UnreadMsgId> unreads) {
      this.unreads = checkForNulls(unreads);
      return this;
    }

    @Override
    public UnreadMsgRes build() {
      return new UnreadMsgRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
