// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 * 拿User Token，可用于激活、登录、绑定
 */
public final class UserTokenReq extends Message {

  public static final String DEFAULT_MACID = "";
  public static final String DEFAULT_MOBILEPHONE = "";
  public static final Boolean DEFAULT_CHECKREPEAT = false;

  @ProtoField(tag = 1, type = STRING)
  public final String macid;

  @ProtoField(tag = 2, type = STRING)
  public final String mobilephone;

  @ProtoField(tag = 3, type = BOOL)
  public final Boolean checkrepeat;

  private UserTokenReq(Builder builder) {
    this.macid = builder.macid;
    this.mobilephone = builder.mobilephone;
    this.checkrepeat = builder.checkrepeat;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserTokenReq)) return false;
    UserTokenReq o = (UserTokenReq) other;
    return equals(macid, o.macid)
        && equals(mobilephone, o.mobilephone)
        && equals(checkrepeat, o.checkrepeat);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = macid != null ? macid.hashCode() : 0;
      result = result * 37 + (mobilephone != null ? mobilephone.hashCode() : 0);
      result = result * 37 + (checkrepeat != null ? checkrepeat.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserTokenReq> {

    public String macid;
    public String mobilephone;
    public Boolean checkrepeat;

    public Builder() {
    }

    public Builder(UserTokenReq message) {
      super(message);
      if (message == null) return;
      this.macid = message.macid;
      this.mobilephone = message.mobilephone;
      this.checkrepeat = message.checkrepeat;
    }

    public Builder macid(String macid) {
      this.macid = macid;
      return this;
    }

    public Builder mobilephone(String mobilephone) {
      this.mobilephone = mobilephone;
      return this;
    }

    public Builder checkrepeat(Boolean checkrepeat) {
      this.checkrepeat = checkrepeat;
      return this;
    }

    @Override
    public UserTokenReq build() {
      return new UserTokenReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
