// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum UserSearchBy
    implements ProtoEnum {
  UserSearchByUnKnow(0),
  UserSearchByKeyWord(1),
  UserSearchByUid(2),
  UserSearchByLivingFans(3),
  /**
   * 关注的人正在直播，根据热度排序
   */
  UserSearchByLivingActive(4),
  /**
   * 正在直播的人，根据热度排序
   */
  UserSearchByLivingTime(5),
  /**
   * 正在直播的人，根据时间排序
   */
  UserSearchBySortOrderTop(6),
  /**
   * 置顶用户
   */
  UserSearchBySortOrderWhite(7),
  /**
   * 白名单用户
   */
  UserSearchBySortOrderBlack(8);

  private final int value;

  private UserSearchBy(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int UserSearchByUnKnow_VALUE = 0;
  public static final int UserSearchByKeyWord_VALUE = 1;
  public static final int UserSearchByUid_VALUE = 2;
  public static final int UserSearchByLivingFans_VALUE = 3;
  /**
   * 关注的人正在直播，根据热度排序
   */
  public static final int UserSearchByLivingActive_VALUE = 4;
  /**
   * 正在直播的人，根据热度排序
   */
  public static final int UserSearchByLivingTime_VALUE = 5;
  /**
   * 正在直播的人，根据时间排序
   */
  public static final int UserSearchBySortOrderTop_VALUE = 6;
  /**
   * 置顶用户
   */
  public static final int UserSearchBySortOrderWhite_VALUE = 7;
  /**
   * 白名单用户
   */
  public static final int UserSearchBySortOrderBlack_VALUE = 8;

  public static UserSearchBy valueOf(int value) {
    switch (value)  {
      case 0: return UserSearchByUnKnow;
      case 1: return UserSearchByKeyWord;
      case 2: return UserSearchByUid;
      case 3: return UserSearchByLivingFans;
      case 4: return UserSearchByLivingActive;
      case 5: return UserSearchByLivingTime;
      case 6: return UserSearchBySortOrderTop;
      case 7: return UserSearchBySortOrderWhite;
      case 8: return UserSearchBySortOrderBlack;
      default: return null;
    }
  }
}
