// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * 批量查看个人资料：
 */
public final class UserInfoListReq extends Message {

  public static final List<Long> DEFAULT_UIDS = Collections.emptyList();

  @ProtoField(tag = 1, type = UINT64, label = REPEATED)
  public final List<Long> uids;

  @ProtoField(tag = 3)
  public final UserInfo template;

  private UserInfoListReq(Builder builder) {
    this.uids = immutableCopyOf(builder.uids);
    this.template = builder.template;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserInfoListReq)) return false;
    UserInfoListReq o = (UserInfoListReq) other;
    return equals(uids, o.uids)
        && equals(template, o.template);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uids != null ? uids.hashCode() : 1;
      result = result * 37 + (template != null ? template.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserInfoListReq> {

    public List<Long> uids;
    public UserInfo template;

    public Builder() {
    }

    public Builder(UserInfoListReq message) {
      super(message);
      if (message == null) return;
      this.uids = copyOf(message.uids);
      this.template = message.template;
    }

    public Builder uids(List<Long> uids) {
      this.uids = checkForNulls(uids);
      return this;
    }

    public Builder template(UserInfo template) {
      this.template = template;
      return this;
    }

    @Override
    public UserInfoListReq build() {
      return new UserInfoListReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
