// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class UserPropReq extends Message {

  public static final Long DEFAULT_UID = 0L;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long uid;

  @ProtoField(tag = 2)
  public final UserProp template;

  private UserPropReq(Builder builder) {
    this.uid = builder.uid;
    this.template = builder.template;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserPropReq)) return false;
    UserPropReq o = (UserPropReq) other;
    return equals(uid, o.uid)
        && equals(template, o.template);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uid != null ? uid.hashCode() : 0;
      result = result * 37 + (template != null ? template.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserPropReq> {

    public Long uid;
    public UserProp template;

    public Builder() {
    }

    public Builder(UserPropReq message) {
      super(message);
      if (message == null) return;
      this.uid = message.uid;
      this.template = message.template;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder template(UserProp template) {
      this.template = template;
      return this;
    }

    @Override
    public UserPropReq build() {
      checkRequiredFields();
      return new UserPropReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
