// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 拿到一个Token和收到一条短信验证码
 */
public final class UserTokenRes extends Message {

  public static final String DEFAULT_TOKEN = "";

  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String token;

  private UserTokenRes(Builder builder) {
    this.token = builder.token;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserTokenRes)) return false;
    return equals(token, ((UserTokenRes) other).token);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = token != null ? token.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<UserTokenRes> {

    public String token;

    public Builder() {
    }

    public Builder(UserTokenRes message) {
      super(message);
      if (message == null) return;
      this.token = message.token;
    }

    public Builder token(String token) {
      this.token = token;
      return this;
    }

    @Override
    public UserTokenRes build() {
      checkRequiredFields();
      return new UserTokenRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
