// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum UserNoticeType
    implements ProtoEnum {
  UserNoticeUnknown(0),
  UserNoticeAwardChip(1),
  /**
   * 奖励筹码
   */
  UserNoticeAwardGold(2);

  private final int value;

  private UserNoticeType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int UserNoticeUnknown_VALUE = 0;
  public static final int UserNoticeAwardChip_VALUE = 1;
  /**
   * 奖励筹码
   */
  public static final int UserNoticeAwardGold_VALUE = 2;

  public static UserNoticeType valueOf(int value) {
    switch (value)  {
      case 0: return UserNoticeUnknown;
      case 1: return UserNoticeAwardChip;
      case 2: return UserNoticeAwardGold;
      default: return null;
    }
  }
}
