// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class UserInviteInfoRes extends Message {

  public static final Long DEFAULT_INVITENUM = 0L;
  public static final Long DEFAULT_GETMGOLD = 0L;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long inviteNum;

  @ProtoField(tag = 2, type = UINT64, label = REQUIRED)
  public final Long getMGold;

  private UserInviteInfoRes(Builder builder) {
    this.inviteNum = builder.inviteNum;
    this.getMGold = builder.getMGold;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserInviteInfoRes)) return false;
    UserInviteInfoRes o = (UserInviteInfoRes) other;
    return equals(inviteNum, o.inviteNum)
        && equals(getMGold, o.getMGold);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = inviteNum != null ? inviteNum.hashCode() : 0;
      result = result * 37 + (getMGold != null ? getMGold.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserInviteInfoRes> {

    public Long inviteNum;
    public Long getMGold;

    public Builder() {
    }

    public Builder(UserInviteInfoRes message) {
      super(message);
      if (message == null) return;
      this.inviteNum = message.inviteNum;
      this.getMGold = message.getMGold;
    }

    public Builder inviteNum(Long inviteNum) {
      this.inviteNum = inviteNum;
      return this;
    }

    public Builder getMGold(Long getMGold) {
      this.getMGold = getMGold;
      return this;
    }

    @Override
    public UserInviteInfoRes build() {
      checkRequiredFields();
      return new UserInviteInfoRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
