// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

/**
 * 退出
 */
public final class UserLogoutReq extends Message {

  private UserLogoutReq(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof UserLogoutReq;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<UserLogoutReq> {

    public Builder() {
    }

    public Builder(UserLogoutReq message) {
      super(message);
    }

    @Override
    public UserLogoutReq build() {
      return new UserLogoutReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
