// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;

public final class UserSearchReq extends Message {

  public static final String DEFAULT_KEYWORD = "";
  public static final Integer DEFAULT_INDEX = 0;
  public static final Integer DEFAULT_FETCHS = 0;
  public static final UserSearchBy DEFAULT_SEARCHBY = UserSearchBy.UserSearchByUnKnow;
  public static final UserSearchOrderBy DEFAULT_ORDERBY = UserSearchOrderBy.UserSearchOrderByDesc;
  public static final SexType DEFAULT_SEX = SexType.Unknow;
  public static final String DEFAULT_LOCATION = "";
  public static final Boolean DEFAULT_LIVING = false;
  public static final Long DEFAULT_SORTKEY = 0L;

  @ProtoField(tag = 1, type = STRING)
  public final String keyword;

  @ProtoField(tag = 2, type = UINT32)
  public final Integer index;

  @ProtoField(tag = 3, type = UINT32)
  public final Integer fetchs;

  @ProtoField(tag = 5, type = ENUM)
  public final UserSearchBy searchby;

  @ProtoField(tag = 6, type = ENUM)
  public final UserSearchOrderBy orderby;

  @ProtoField(tag = 7, type = ENUM)
  public final SexType sex;

  /**
   * 性别过滤
   */
  @ProtoField(tag = 8, type = STRING)
  public final String location;

  /**
   * 地理位置过滤
   */
  @ProtoField(tag = 9, type = BOOL)
  public final Boolean living;

  /**
   * 正在直播
   */
  @ProtoField(tag = 19, type = INT64)
  public final Long sortkey;

  /**
   * Cache用的，UserSearchRes返回了什么，在请问下一页的时候带上
   */
  @ProtoField(tag = 20)
  public final UserInfo template;

  private UserSearchReq(Builder builder) {
    this.keyword = builder.keyword;
    this.index = builder.index;
    this.fetchs = builder.fetchs;
    this.searchby = builder.searchby;
    this.orderby = builder.orderby;
    this.sex = builder.sex;
    this.location = builder.location;
    this.living = builder.living;
    this.sortkey = builder.sortkey;
    this.template = builder.template;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserSearchReq)) return false;
    UserSearchReq o = (UserSearchReq) other;
    return equals(keyword, o.keyword)
        && equals(index, o.index)
        && equals(fetchs, o.fetchs)
        && equals(searchby, o.searchby)
        && equals(orderby, o.orderby)
        && equals(sex, o.sex)
        && equals(location, o.location)
        && equals(living, o.living)
        && equals(sortkey, o.sortkey)
        && equals(template, o.template);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = keyword != null ? keyword.hashCode() : 0;
      result = result * 37 + (index != null ? index.hashCode() : 0);
      result = result * 37 + (fetchs != null ? fetchs.hashCode() : 0);
      result = result * 37 + (searchby != null ? searchby.hashCode() : 0);
      result = result * 37 + (orderby != null ? orderby.hashCode() : 0);
      result = result * 37 + (sex != null ? sex.hashCode() : 0);
      result = result * 37 + (location != null ? location.hashCode() : 0);
      result = result * 37 + (living != null ? living.hashCode() : 0);
      result = result * 37 + (sortkey != null ? sortkey.hashCode() : 0);
      result = result * 37 + (template != null ? template.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserSearchReq> {

    public String keyword;
    public Integer index;
    public Integer fetchs;
    public UserSearchBy searchby;
    public UserSearchOrderBy orderby;
    public SexType sex;
    public String location;
    public Boolean living;
    public Long sortkey;
    public UserInfo template;

    public Builder() {
    }

    public Builder(UserSearchReq message) {
      super(message);
      if (message == null) return;
      this.keyword = message.keyword;
      this.index = message.index;
      this.fetchs = message.fetchs;
      this.searchby = message.searchby;
      this.orderby = message.orderby;
      this.sex = message.sex;
      this.location = message.location;
      this.living = message.living;
      this.sortkey = message.sortkey;
      this.template = message.template;
    }

    public Builder keyword(String keyword) {
      this.keyword = keyword;
      return this;
    }

    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    public Builder fetchs(Integer fetchs) {
      this.fetchs = fetchs;
      return this;
    }

    public Builder searchby(UserSearchBy searchby) {
      this.searchby = searchby;
      return this;
    }

    public Builder orderby(UserSearchOrderBy orderby) {
      this.orderby = orderby;
      return this;
    }

    public Builder sex(SexType sex) {
      this.sex = sex;
      return this;
    }

    /**
     * 性别过滤
     */
    public Builder location(String location) {
      this.location = location;
      return this;
    }

    /**
     * 地理位置过滤
     */
    public Builder living(Boolean living) {
      this.living = living;
      return this;
    }

    /**
     * 正在直播
     */
    public Builder sortkey(Long sortkey) {
      this.sortkey = sortkey;
      return this;
    }

    /**
     * Cache用的，UserSearchRes返回了什么，在请问下一页的时候带上
     */
    public Builder template(UserInfo template) {
      this.template = template;
      return this;
    }

    @Override
    public UserSearchReq build() {
      return new UserSearchReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
