// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 验证用户
 */
public final class UserLoginVerifyReq extends Message {

  public static final LoginBy DEFAULT_LOGINBY = LoginBy.LoginBy_Mac;
  public static final String DEFAULT_MACID = "";
  public static final String DEFAULT_TOKEN = "";
  public static final String DEFAULT_IDENTIFYINGCODE = "";

  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final LoginBy loginBy;

  @ProtoField(tag = 2, type = STRING)
  public final String macid;

  @ProtoField(tag = 4, type = STRING)
  public final String token;

  @ProtoField(tag = 5, type = STRING, label = REQUIRED)
  public final String identifyingCode;

  private UserLoginVerifyReq(Builder builder) {
    this.loginBy = builder.loginBy;
    this.macid = builder.macid;
    this.token = builder.token;
    this.identifyingCode = builder.identifyingCode;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserLoginVerifyReq)) return false;
    UserLoginVerifyReq o = (UserLoginVerifyReq) other;
    return equals(loginBy, o.loginBy)
        && equals(macid, o.macid)
        && equals(token, o.token)
        && equals(identifyingCode, o.identifyingCode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = loginBy != null ? loginBy.hashCode() : 0;
      result = result * 37 + (macid != null ? macid.hashCode() : 0);
      result = result * 37 + (token != null ? token.hashCode() : 0);
      result = result * 37 + (identifyingCode != null ? identifyingCode.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserLoginVerifyReq> {

    public LoginBy loginBy;
    public String macid;
    public String token;
    public String identifyingCode;

    public Builder() {
    }

    public Builder(UserLoginVerifyReq message) {
      super(message);
      if (message == null) return;
      this.loginBy = message.loginBy;
      this.macid = message.macid;
      this.token = message.token;
      this.identifyingCode = message.identifyingCode;
    }

    public Builder loginBy(LoginBy loginBy) {
      this.loginBy = loginBy;
      return this;
    }

    public Builder macid(String macid) {
      this.macid = macid;
      return this;
    }

    public Builder token(String token) {
      this.token = token;
      return this;
    }

    public Builder identifyingCode(String identifyingCode) {
      this.identifyingCode = identifyingCode;
      return this;
    }

    @Override
    public UserLoginVerifyReq build() {
      checkRequiredFields();
      return new UserLoginVerifyReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
