// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

public final class UserLoginVerifyRes extends Message {

  private UserLoginVerifyRes(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof UserLoginVerifyRes;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<UserLoginVerifyRes> {

    public Builder() {
    }

    public Builder(UserLoginVerifyRes message) {
      super(message);
    }

    @Override
    public UserLoginVerifyRes build() {
      return new UserLoginVerifyRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
