// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class UserWebLoginReq extends Message {

  public static final String DEFAULT_VERIFYCODE = "";
  public static final Long DEFAULT_UID = 0L;
  public static final Integer DEFAULT_ROLETYPE = 0;
  public static final String DEFAULT_PASSWORD = "";
  public static final String DEFAULT_MOBILEPHONE = "";
  public static final Boolean DEFAULT_QMODE = false;

  @ProtoField(tag = 1, type = STRING)
  public final String verifycode;

  @ProtoField(tag = 100, type = UINT64)
  public final Long uid;

  @ProtoField(tag = 101, type = UINT32)
  public final Integer roletype;

  @ProtoField(tag = 102, type = STRING)
  public final String password;

  @ProtoField(tag = 103, type = STRING)
  public final String mobilephone;

  @ProtoField(tag = 104, type = BOOL)
  public final Boolean qmode;

  private UserWebLoginReq(Builder builder) {
    this.verifycode = builder.verifycode;
    this.uid = builder.uid;
    this.roletype = builder.roletype;
    this.password = builder.password;
    this.mobilephone = builder.mobilephone;
    this.qmode = builder.qmode;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserWebLoginReq)) return false;
    UserWebLoginReq o = (UserWebLoginReq) other;
    return equals(verifycode, o.verifycode)
        && equals(uid, o.uid)
        && equals(roletype, o.roletype)
        && equals(password, o.password)
        && equals(mobilephone, o.mobilephone)
        && equals(qmode, o.qmode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = verifycode != null ? verifycode.hashCode() : 0;
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      result = result * 37 + (roletype != null ? roletype.hashCode() : 0);
      result = result * 37 + (password != null ? password.hashCode() : 0);
      result = result * 37 + (mobilephone != null ? mobilephone.hashCode() : 0);
      result = result * 37 + (qmode != null ? qmode.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserWebLoginReq> {

    public String verifycode;
    public Long uid;
    public Integer roletype;
    public String password;
    public String mobilephone;
    public Boolean qmode;

    public Builder() {
    }

    public Builder(UserWebLoginReq message) {
      super(message);
      if (message == null) return;
      this.verifycode = message.verifycode;
      this.uid = message.uid;
      this.roletype = message.roletype;
      this.password = message.password;
      this.mobilephone = message.mobilephone;
      this.qmode = message.qmode;
    }

    public Builder verifycode(String verifycode) {
      this.verifycode = verifycode;
      return this;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder roletype(Integer roletype) {
      this.roletype = roletype;
      return this;
    }

    public Builder password(String password) {
      this.password = password;
      return this;
    }

    public Builder mobilephone(String mobilephone) {
      this.mobilephone = mobilephone;
      return this;
    }

    public Builder qmode(Boolean qmode) {
      this.qmode = qmode;
      return this;
    }

    @Override
    public UserWebLoginReq build() {
      return new UserWebLoginReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
