// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 修改密码
 */
public final class UserPasswordModifyReq extends Message {

  public static final String DEFAULT_NEWPASSWORD = "";
  public static final String DEFAULT_OLDPASSWORD = "";

  /**
   * 这个字段表示客户端本地存储的会话消息的流水号
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String newpassword;

  @ProtoField(tag = 2, type = STRING)
  public final String oldpassword;

  private UserPasswordModifyReq(Builder builder) {
    this.newpassword = builder.newpassword;
    this.oldpassword = builder.oldpassword;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserPasswordModifyReq)) return false;
    UserPasswordModifyReq o = (UserPasswordModifyReq) other;
    return equals(newpassword, o.newpassword)
        && equals(oldpassword, o.oldpassword);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = newpassword != null ? newpassword.hashCode() : 0;
      result = result * 37 + (oldpassword != null ? oldpassword.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UserPasswordModifyReq> {

    public String newpassword;
    public String oldpassword;

    public Builder() {
    }

    public Builder(UserPasswordModifyReq message) {
      super(message);
      if (message == null) return;
      this.newpassword = message.newpassword;
      this.oldpassword = message.oldpassword;
    }

    /**
     * 这个字段表示客户端本地存储的会话消息的流水号
     */
    public Builder newpassword(String newpassword) {
      this.newpassword = newpassword;
      return this;
    }

    public Builder oldpassword(String oldpassword) {
      this.oldpassword = oldpassword;
      return this;
    }

    @Override
    public UserPasswordModifyReq build() {
      checkRequiredFields();
      return new UserPasswordModifyReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
