// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum UserForbidMethod
    implements ProtoEnum {
  ForbidUid(1),
  /**
   * 封号
   */
  ForbidMac(2),
  /**
   * 封设备
   */
  ForbidIp(4),
  /**
   * 封IP
   */
  ForbidLive(8);

  private final int value;

  private UserForbidMethod(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int ForbidUid_VALUE = 1;
  /**
   * 封号
   */
  public static final int ForbidMac_VALUE = 2;
  /**
   * 封设备
   */
  public static final int ForbidIp_VALUE = 4;
  /**
   * 封IP
   */
  public static final int ForbidLive_VALUE = 8;

  public static UserForbidMethod valueOf(int value) {
    switch (value)  {
      case 1: return ForbidUid;
      case 2: return ForbidMac;
      case 4: return ForbidIp;
      case 8: return ForbidLive;
      default: return null;
    }
  }
}
