// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum ViolatorReason
    implements ProtoEnum {
  ViolatorReasonAdvertisement(1),
  /**
   * 垃圾广告
   */
  ViolatorReasonHarassment(2),
  /**
   * 恶意骚扰
   */
  ViolatorReasonSex(3),
  /**
   * 色情
   */
  ViolatorReasonPolitical(4),
  /**
   * 政治敏感
   */
  ViolatorReasonAttack(5),
  /**
   * 人身攻击
   */
  ViolatorReasonPseudo(6),
  /**
   * 不实信息
   */
  ViolatorReasonFakeWinning(7),
  /**
   * 虚假中奖
   */
  ViolatorReasonVideo(11),
  /**
   * 视频违规S01
   */
  ViolatorReasonVoice(21),
  /**
   * 音频违规S02
   */
  ViolatorReasonOther(99);

  private final int value;

  private ViolatorReason(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int ViolatorReasonAdvertisement_VALUE = 1;
  /**
   * 垃圾广告
   */
  public static final int ViolatorReasonHarassment_VALUE = 2;
  /**
   * 恶意骚扰
   */
  public static final int ViolatorReasonSex_VALUE = 3;
  /**
   * 色情
   */
  public static final int ViolatorReasonPolitical_VALUE = 4;
  /**
   * 政治敏感
   */
  public static final int ViolatorReasonAttack_VALUE = 5;
  /**
   * 人身攻击
   */
  public static final int ViolatorReasonPseudo_VALUE = 6;
  /**
   * 不实信息
   */
  public static final int ViolatorReasonFakeWinning_VALUE = 7;
  /**
   * 虚假中奖
   */
  public static final int ViolatorReasonVideo_VALUE = 11;
  /**
   * 视频违规S01
   */
  public static final int ViolatorReasonVoice_VALUE = 21;
  /**
   * 音频违规S02
   */
  public static final int ViolatorReasonOther_VALUE = 99;

  public static ViolatorReason valueOf(int value) {
    switch (value)  {
      case 1: return ViolatorReasonAdvertisement;
      case 2: return ViolatorReasonHarassment;
      case 3: return ViolatorReasonSex;
      case 4: return ViolatorReasonPolitical;
      case 5: return ViolatorReasonAttack;
      case 6: return ViolatorReasonPseudo;
      case 7: return ViolatorReasonFakeWinning;
      case 11: return ViolatorReasonVideo;
      case 21: return ViolatorReasonVoice;
      case 99: return ViolatorReasonOther;
      default: return null;
    }
  }
}
