// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class WealthDrawYYBindRes extends Message {

  public static final Integer DEFAULT_BINDID = 0;
  public static final Long DEFAULT_YYNO = 0L;
  public static final Long DEFAULT_YYUID = 0L;
  public static final String DEFAULT_YYNICK = "";
  public static final Long DEFAULT_CORPUID = 0L;

  @ProtoField(tag = 1, type = UINT32)
  public final Integer bindid;

  @ProtoField(tag = 10, type = UINT64)
  public final Long yyNo;

  /**
   * 绑定的YY号
   */
  @ProtoField(tag = 11, type = UINT64)
  public final Long yyUid;

  @ProtoField(tag = 12, type = STRING)
  public final String yyNick;

  @ProtoField(tag = 20, type = UINT64)
  public final Long corpUid;

  /**
   * 绑定的公会(美美玩UID)
   */
  @ProtoField(tag = 21)
  public final UserInfo corpInfo;

  private WealthDrawYYBindRes(Builder builder) {
    this.bindid = builder.bindid;
    this.yyNo = builder.yyNo;
    this.yyUid = builder.yyUid;
    this.yyNick = builder.yyNick;
    this.corpUid = builder.corpUid;
    this.corpInfo = builder.corpInfo;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WealthDrawYYBindRes)) return false;
    WealthDrawYYBindRes o = (WealthDrawYYBindRes) other;
    return equals(bindid, o.bindid)
        && equals(yyNo, o.yyNo)
        && equals(yyUid, o.yyUid)
        && equals(yyNick, o.yyNick)
        && equals(corpUid, o.corpUid)
        && equals(corpInfo, o.corpInfo);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = bindid != null ? bindid.hashCode() : 0;
      result = result * 37 + (yyNo != null ? yyNo.hashCode() : 0);
      result = result * 37 + (yyUid != null ? yyUid.hashCode() : 0);
      result = result * 37 + (yyNick != null ? yyNick.hashCode() : 0);
      result = result * 37 + (corpUid != null ? corpUid.hashCode() : 0);
      result = result * 37 + (corpInfo != null ? corpInfo.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<WealthDrawYYBindRes> {

    public Integer bindid;
    public Long yyNo;
    public Long yyUid;
    public String yyNick;
    public Long corpUid;
    public UserInfo corpInfo;

    public Builder() {
    }

    public Builder(WealthDrawYYBindRes message) {
      super(message);
      if (message == null) return;
      this.bindid = message.bindid;
      this.yyNo = message.yyNo;
      this.yyUid = message.yyUid;
      this.yyNick = message.yyNick;
      this.corpUid = message.corpUid;
      this.corpInfo = message.corpInfo;
    }

    public Builder bindid(Integer bindid) {
      this.bindid = bindid;
      return this;
    }

    public Builder yyNo(Long yyNo) {
      this.yyNo = yyNo;
      return this;
    }

    /**
     * 绑定的YY号
     */
    public Builder yyUid(Long yyUid) {
      this.yyUid = yyUid;
      return this;
    }

    public Builder yyNick(String yyNick) {
      this.yyNick = yyNick;
      return this;
    }

    public Builder corpUid(Long corpUid) {
      this.corpUid = corpUid;
      return this;
    }

    /**
     * 绑定的公会(美美玩UID)
     */
    public Builder corpInfo(UserInfo corpInfo) {
      this.corpInfo = corpInfo;
      return this;
    }

    @Override
    public WealthDrawYYBindRes build() {
      return new WealthDrawYYBindRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
