// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

/**
 * 获取设置主播或企业号的列表
 */
public final class WealthDrawCorpListReq extends Message {

  public static final Boolean DEFAULT_CORP = false;

  @ProtoField(tag = 1, type = BOOL)
  public final Boolean corp;

  private WealthDrawCorpListReq(Builder builder) {
    this.corp = builder.corp;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WealthDrawCorpListReq)) return false;
    return equals(corp, ((WealthDrawCorpListReq) other).corp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = corp != null ? corp.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<WealthDrawCorpListReq> {

    public Boolean corp;

    public Builder() {
    }

    public Builder(WealthDrawCorpListReq message) {
      super(message);
      if (message == null) return;
      this.corp = message.corp;
    }

    public Builder corp(Boolean corp) {
      this.corp = corp;
      return this;
    }

    @Override
    public WealthDrawCorpListReq build() {
      return new WealthDrawCorpListReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
