// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 绑定
 */
public final class WealthDrawBindReq extends Message {

  @ProtoField(tag = 1, label = REQUIRED)
  public final BindInfo bind;

  private WealthDrawBindReq(Builder builder) {
    this.bind = builder.bind;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WealthDrawBindReq)) return false;
    return equals(bind, ((WealthDrawBindReq) other).bind);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = bind != null ? bind.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<WealthDrawBindReq> {

    public BindInfo bind;

    public Builder() {
    }

    public Builder(WealthDrawBindReq message) {
      super(message);
      if (message == null) return;
      this.bind = message.bind;
    }

    public Builder bind(BindInfo bind) {
      this.bind = bind;
      return this;
    }

    @Override
    public WealthDrawBindReq build() {
      checkRequiredFields();
      return new WealthDrawBindReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
