// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 设置个人财富值
 */
public final class WealthSetTestReq extends Message {

  public static final Integer DEFAULT_WHAT = 0;
  public static final Long DEFAULT_UID = 0L;
  public static final Long DEFAULT_NUM = 0L;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer what;

  @ProtoField(tag = 2, type = UINT64, label = REQUIRED)
  public final Long uid;

  @ProtoField(tag = 3, type = UINT64, label = REQUIRED)
  public final Long num;

  private WealthSetTestReq(Builder builder) {
    this.what = builder.what;
    this.uid = builder.uid;
    this.num = builder.num;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WealthSetTestReq)) return false;
    WealthSetTestReq o = (WealthSetTestReq) other;
    return equals(what, o.what)
        && equals(uid, o.uid)
        && equals(num, o.num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = what != null ? what.hashCode() : 0;
      result = result * 37 + (uid != null ? uid.hashCode() : 0);
      result = result * 37 + (num != null ? num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<WealthSetTestReq> {

    public Integer what;
    public Long uid;
    public Long num;

    public Builder() {
    }

    public Builder(WealthSetTestReq message) {
      super(message);
      if (message == null) return;
      this.what = message.what;
      this.uid = message.uid;
      this.num = message.num;
    }

    public Builder what(Integer what) {
      this.what = what;
      return this;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder num(Long num) {
      this.num = num;
      return this;
    }

    @Override
    public WealthSetTestReq build() {
      checkRequiredFields();
      return new WealthSetTestReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
