// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT64;

/**
 * 绑定YY签约号,yyNo和corpUid都不填可查询绑定信息,APP内部访问
 */
public final class WealthDrawYYBindReq extends Message {

  public static final Long DEFAULT_YYNO = 0L;
  public static final Long DEFAULT_CORPUID = 0L;

  @ProtoField(tag = 1, type = UINT64)
  public final Long yyNo;

  /**
   * 绑定的YY号
   */
  @ProtoField(tag = 2, type = UINT64)
  public final Long corpUid;

  private WealthDrawYYBindReq(Builder builder) {
    this.yyNo = builder.yyNo;
    this.corpUid = builder.corpUid;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WealthDrawYYBindReq)) return false;
    WealthDrawYYBindReq o = (WealthDrawYYBindReq) other;
    return equals(yyNo, o.yyNo)
        && equals(corpUid, o.corpUid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = yyNo != null ? yyNo.hashCode() : 0;
      result = result * 37 + (corpUid != null ? corpUid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<WealthDrawYYBindReq> {

    public Long yyNo;
    public Long corpUid;

    public Builder() {
    }

    public Builder(WealthDrawYYBindReq message) {
      super(message);
      if (message == null) return;
      this.yyNo = message.yyNo;
      this.corpUid = message.corpUid;
    }

    public Builder yyNo(Long yyNo) {
      this.yyNo = yyNo;
      return this;
    }

    /**
     * 绑定的YY号
     */
    public Builder corpUid(Long corpUid) {
      this.corpUid = corpUid;
      return this;
    }

    @Override
    public WealthDrawYYBindReq build() {
      return new WealthDrawYYBindReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
