// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class WealthDrawBindRes extends Message {

  public static final String DEFAULT_URL = "";

  @ProtoField(tag = 1, type = STRING)
  public final String url;

  private WealthDrawBindRes(Builder builder) {
    this.url = builder.url;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WealthDrawBindRes)) return false;
    return equals(url, ((WealthDrawBindRes) other).url);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = url != null ? url.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<WealthDrawBindRes> {

    public String url;

    public Builder() {
    }

    public Builder(WealthDrawBindRes message) {
      super(message);
      if (message == null) return;
      this.url = message.url;
    }

    public Builder url(String url) {
      this.url = url;
      return this;
    }

    @Override
    public WealthDrawBindRes build() {
      return new WealthDrawBindRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
