// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;

public final class WealthDrawYYBindSetRes extends Message {

  public static final Integer DEFAULT_BINDID = 0;

  @ProtoField(tag = 1, type = UINT32)
  public final Integer bindid;

  private WealthDrawYYBindSetRes(Builder builder) {
    this.bindid = builder.bindid;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WealthDrawYYBindSetRes)) return false;
    return equals(bindid, ((WealthDrawYYBindSetRes) other).bindid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = bindid != null ? bindid.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<WealthDrawYYBindSetRes> {

    public Integer bindid;

    public Builder() {
    }

    public Builder(WealthDrawYYBindSetRes message) {
      super(message);
      if (message == null) return;
      this.bindid = message.bindid;
    }

    public Builder bindid(Integer bindid) {
      this.bindid = bindid;
      return this;
    }

    @Override
    public WealthDrawYYBindSetRes build() {
      return new WealthDrawYYBindSetRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
