// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;

/**
 * 本月工资、分成发放列表查询
 */
public final class WealthDrawManualListReq extends Message {

  private WealthDrawManualListReq(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof WealthDrawManualListReq;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<WealthDrawManualListReq> {

    public Builder() {
    }

    public Builder(WealthDrawManualListReq message) {
      super(message);
    }

    @Override
    public WealthDrawManualListReq build() {
      return new WealthDrawManualListReq(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
