// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.ProtoEnum;

public enum WealthDrawState
    implements ProtoEnum {
  DrawStateCheck(1),
  /**
   * 客户端显示发放中   实际是验证中
   */
  DrawStateIssue(2),
  /**
   * 发放中
   */
  DrawStateFail1(3),
  /**
   * 提取失败1
   */
  DrawStateFail2(4),
  /**
   * 提取失败2
   */
  DrawStateFail3(5),
  /**
   * 提取失败3
   */
  DrawStateFail4(6),
  /**
   * 提取失败4
   */
  DrawStateFinish(10);

  private final int value;

  private WealthDrawState(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public static final int DrawStateCheck_VALUE = 1;
  /**
   * 客户端显示发放中   实际是验证中
   */
  public static final int DrawStateIssue_VALUE = 2;
  /**
   * 发放中
   */
  public static final int DrawStateFail1_VALUE = 3;
  /**
   * 提取失败1
   */
  public static final int DrawStateFail2_VALUE = 4;
  /**
   * 提取失败2
   */
  public static final int DrawStateFail3_VALUE = 5;
  /**
   * 提取失败3
   */
  public static final int DrawStateFail4_VALUE = 6;
  /**
   * 提取失败4
   */
  public static final int DrawStateFinish_VALUE = 10;

  public static WealthDrawState valueOf(int value) {
    switch (value)  {
      case 1: return DrawStateCheck;
      case 2: return DrawStateIssue;
      case 3: return DrawStateFail1;
      case 4: return DrawStateFail2;
      case 5: return DrawStateFail3;
      case 6: return DrawStateFail4;
      case 10: return DrawStateFinish;
      default: return null;
    }
  }
}
