// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.FLOAT;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class WealthDrawTaxRes extends Message {

  public static final Float DEFAULT_MONEY = 0F;
  public static final Float DEFAULT_TAXMONEY = 0F;

  @ProtoField(tag = 1, type = FLOAT, label = REQUIRED)
  public final Float money;

  /**
   * 提取钱数值
   */
  @ProtoField(tag = 2, type = FLOAT, label = REQUIRED)
  public final Float taxMoney;

  private WealthDrawTaxRes(Builder builder) {
    this.money = builder.money;
    this.taxMoney = builder.taxMoney;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WealthDrawTaxRes)) return false;
    WealthDrawTaxRes o = (WealthDrawTaxRes) other;
    return equals(money, o.money)
        && equals(taxMoney, o.taxMoney);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = money != null ? money.hashCode() : 0;
      result = result * 37 + (taxMoney != null ? taxMoney.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<WealthDrawTaxRes> {

    public Float money;
    public Float taxMoney;

    public Builder() {
    }

    public Builder(WealthDrawTaxRes message) {
      super(message);
      if (message == null) return;
      this.money = message.money;
      this.taxMoney = message.taxMoney;
    }

    public Builder money(Float money) {
      this.money = money;
      return this;
    }

    /**
     * 提取钱数值
     */
    public Builder taxMoney(Float taxMoney) {
      this.taxMoney = taxMoney;
      return this;
    }

    @Override
    public WealthDrawTaxRes build() {
      checkRequiredFields();
      return new WealthDrawTaxRes(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
