// Code generated by Wire protocol buffer compiler, do not edit.
// Any Question Please Contact: jerryzhou@outlook.com
package protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Datatype.UINT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class WinChipRank extends Message {

  public static final Long DEFAULT_UID = 0L;
  public static final String DEFAULT_NAME = "";
  public static final SexType DEFAULT_SEX = SexType.Unknow;
  public static final String DEFAULT_LOGO = "";
  public static final Integer DEFAULT_LV = 0;
  public static final Long DEFAULT_VAL = 0L;

  @ProtoField(tag = 1, type = UINT64, label = REQUIRED)
  public final Long uid;

  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String name;

  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final SexType sex;

  @ProtoField(tag = 4, type = STRING, label = REQUIRED)
  public final String logo;

  @ProtoField(tag = 5, type = UINT32, label = REQUIRED)
  public final Integer lv;

  @ProtoField(tag = 6, type = UINT64, label = REQUIRED)
  public final Long val;

  private WinChipRank(Builder builder) {
    this.uid = builder.uid;
    this.name = builder.name;
    this.sex = builder.sex;
    this.logo = builder.logo;
    this.lv = builder.lv;
    this.val = builder.val;
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WinChipRank)) return false;
    WinChipRank o = (WinChipRank) other;
    return equals(uid, o.uid)
        && equals(name, o.name)
        && equals(sex, o.sex)
        && equals(logo, o.logo)
        && equals(lv, o.lv)
        && equals(val, o.val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uid != null ? uid.hashCode() : 0;
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (sex != null ? sex.hashCode() : 0);
      result = result * 37 + (logo != null ? logo.hashCode() : 0);
      result = result * 37 + (lv != null ? lv.hashCode() : 0);
      result = result * 37 + (val != null ? val.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<WinChipRank> {

    public Long uid;
    public String name;
    public SexType sex;
    public String logo;
    public Integer lv;
    public Long val;

    public Builder() {
    }

    public Builder(WinChipRank message) {
      super(message);
      if (message == null) return;
      this.uid = message.uid;
      this.name = message.name;
      this.sex = message.sex;
      this.logo = message.logo;
      this.lv = message.lv;
      this.val = message.val;
    }

    public Builder uid(Long uid) {
      this.uid = uid;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder sex(SexType sex) {
      this.sex = sex;
      return this;
    }

    public Builder logo(String logo) {
      this.logo = logo;
      return this;
    }

    public Builder lv(Integer lv) {
      this.lv = lv;
      return this;
    }

    public Builder val(Long val) {
      this.val = val;
      return this;
    }

    @Override
    public WinChipRank build() {
      checkRequiredFields();
      return new WinChipRank(this);
    }
  }

  public static Builder newBuilder() {
    return new Builder();
  }
}
